# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Pacific/Auckland"
    assignees:
       - "rhyskoedijk"
    labels:
      - "dependencies"
    groups:
      azure:
        patterns: ['Azure.*']
      microsoft:
        patterns: ["Microsoft.*"]
      sixlabors:
        patterns: ["SixLabors.*"]
      swashbuckle:
        patterns: ["Swashbuckle.*"]
      system:
        patterns: ["System.*"]
      xunit:
        patterns: ["xunit.*"]
    ignore:
      - dependency-name: "Syncfusion.*" # Must be updated manually as it requires a license
