using System;
using System.Drawing;

namespace SCMM.Shared.API;

/// <remarks>
/// https://www.color-blindness.com/color-name-hue-tool/js/ntc.js
/// </remarks>
public static class ColourName
{
    public struct ColourShadeRgbHsl
    {
        public string Colour;
        public string ColourName;
        public string Shade;
        public string ShadeName;
        public byte R;
        public byte G;
        public byte B;
        public byte H;
        public byte S;
        public byte L;
    }

    private static readonly ColourShadeRgbHsl[] ColorShadeRgbHslLookupTable;

    static ColourName()
    {
        ColorShadeRgbHslLookupTable = ColorTable
            .Select(c =>
            {
                var rgb = GetRGB(c[0]);
                var hsl = GetHSL(c[0]);
                return new ColourShadeRgbHsl()
                {
                    Colour = c[0],
                    ColourName = c[1],
                    Shade = ShadeTable.First(s => s[1] == c[2])[0],
                    ShadeName = c[2],
                    R = rgb[0],
                    G = rgb[1],
                    B = rgb[2],
                    H = hsl[0],
                    S = hsl[1],
                    L = hsl[2]
                };
            })
            .ToArray();
    }

    public static ColourShadeRgbHsl? FindClosestMatch(string htmlColor)
    {
        htmlColor = htmlColor.ToUpper();
        var closestMatch = (ColourShadeRgbHsl?)null;
        var rgb = ColorTranslator.FromHtml(htmlColor);
        var r = rgb.R;
        var g = rgb.G;
        var b = rgb.B;
        var hsl = GetHSL(r, g, b);
        var h = hsl[0];
        var s = hsl[1];
        var l = hsl[2];
        double ndf1 = 0;
        double ndf2 = 0;
        double ndf = 0;
        double df = -1;

        foreach (var item in ColorShadeRgbHslLookupTable)
        {
            if (item.Colour == htmlColor.Trim('#'))
            {
                return item;
            }

            ndf1 = Math.Pow(r - item.R, 2) + Math.Pow(g - item.G, 2) + Math.Pow(b - item.B, 2);
            ndf2 = Math.Abs(Math.Pow(h - item.H, 2)) + Math.Pow(s - item.S, 2) + Math.Abs(Math.Pow(l - item.L, 2));
            ndf = ndf1 + ndf2 * 2;
            if (df < 0 || df > ndf)
            {
                df = ndf;
                closestMatch = item;
            }
        }

        return closestMatch;
    }

    private static byte[] GetRGB(string htmlColour)
    {
        var rgb = ColorTranslator.FromHtml($"#{htmlColour}");
        return new[] { rgb.R, rgb.G, rgb.B };
    }

    private static byte[] GetHSL(string htmlColour)
    {
        var rgb = ColorTranslator.FromHtml($"#{htmlColour}");
        return GetHSL(rgb.R, rgb.G, rgb.B);
    }

    private static byte[] GetHSL(byte r, byte g, byte b)
    {
        var min = Math.Min(r, Math.Min(g, b));
        var max = Math.Max(r, Math.Max(g, b));
        double delta = max - min;
        double l = (min + max) / 2;

        double s = 0;
        if (l > 0 && l < 1)
        {
            s = delta / (l < 0.5 ? 2 * l : 2 - 2 * l);
        }

        double h = 0;
        if (delta > 0)
        {
            if (max == r && max != g)
            {
                h += (g - b) / delta;
            }
            if (max == g && max != b)
            {
                h += 2 + (b - r) / delta;
            }
            if (max == b && max != r)
            {
                h += 4 + (r - g) / delta;
            }
            h /= 6;
        }

        return new byte[]
        {
            (byte)(h * 255),
            (byte)(s * 255),
            (byte)(l * 255)
        };
    }

    private static readonly string[][] ColorTable = new[]
    {
        new [] { "35312C", "Acadia", "Brown" },
        new [] { "75AA94", "Acapulco", "Green" },
        new [] { "C0E8D5", "Aero Blue", "Green" },
        new [] { "745085", "Affair", "Violet" },
        new [] { "905E26", "Afghan Tan", "Yellow" },
        new [] { "5D8AA8", "Air Force Blue", "Blue" },
        new [] { "BEB29A", "Akaroa", "Yellow" },
        new [] { "F2F0E6", "Alabaster", "Grey" },
        new [] { "E1DACB", "Albescent White", "Yellow" },
        new [] { "954E2C", "Alert Tan", "Orange" },
        new [] { "F0F8FF", "Alice Blue", "Blue" },
        new [] { "E32636", "Alizarin", "Red" },
        new [] { "1F6A7D", "Allports", "Blue" },
        new [] { "EED9C4", "Almond", "Yellow" },
        new [] { "9A8678", "Almond Frost", "Brown" },
        new [] { "AD8A3B", "Alpine", "Yellow" },
        new [] { "CDC6C5", "Alto", "Grey" },
        new [] { "848789", "Aluminium", "Grey" },
        new [] { "E52B50", "Amaranth", "Red" },
        new [] { "387B54", "Amazon", "Green" },
        new [] { "FFBF00", "Amber", "Yellow" },
        new [] { "8A7D72", "Americano", "Brown" },
        new [] { "9966CC", "Amethyst", "Violet" },
        new [] { "95879C", "Amethyst Smoke", "Violet" },
        new [] { "F5E6EA", "Amour", "Violet" },
        new [] { "7D9D72", "Amulet", "Green" },
        new [] { "8CCEEA", "Anakiwa", "Blue" },
        new [] { "6C461F", "Antique Brass", "Orange" },
        new [] { "FAEBD7", "Antique White", "White" },
        new [] { "C68E3F", "Anzac", "Yellow" },
        new [] { "D3A95C", "Apache", "Yellow" },
        new [] { "66B348", "Apple", "Green" },
        new [] { "A95249", "Apple Blossom", "Red" },
        new [] { "DEEADC", "Apple Green", "Green" },
        new [] { "FBCEB1", "Apricot", "Orange" },
        new [] { "F7F0DB", "Apricot White", "Yellow" },
        new [] { "00FFFF", "Aqua", "Blue" },
        new [] { "D9DDD5", "Aqua Haze", "Grey" },
        new [] { "E8F3E8", "Aqua Spring", "Green" },
        new [] { "DBE4DC", "Aqua Squeeze", "Grey" },
        new [] { "7FFFD4", "Aquamarine", "Blue" },
        new [] { "274A5D", "Arapawa", "Blue" },
        new [] { "484A46", "Armadillo", "Grey" },
        new [] { "4B5320", "Army green", "Green" },
        new [] { "827A67", "Arrowtown", "Yellow" },
        new [] { "3B444B", "Arsenic", "Grey" },
        new [] { "BEBAA7", "Ash", "Green" },
        new [] { "7BA05B", "Asparagus", "Green" },
        new [] { "EDD5A6", "Astra", "Yellow" },
        new [] { "376F89", "Astral", "Blue" },
        new [] { "445172", "Astronaut", "Blue" },
        new [] { "214559", "Astronaut Blue", "Blue" },
        new [] { "DCDDDD", "Athens Grey", "Grey" },
        new [] { "D5CBB2", "Aths Special", "Yellow" },
        new [] { "9CD03B", "Atlantis", "Green" },
        new [] { "2B797A", "Atoll", "Green" },
        new [] { "3D4B52", "Atomic", "Blue" },
        new [] { "FF9966", "Atomic Tangerine", "Orange" },
        new [] { "9E6759", "Au Chico", "Brown" },
        new [] { "372528", "Aubergine", "Brown" },
        new [] { "712F2C", "Auburn", "Brown" },
        new [] { "EFF8AA", "Australian Mint", "Green" },
        new [] { "95986B", "Avocado", "Green" },
        new [] { "63775A", "Axolotl", "Green" },
        new [] { "F9C0C4", "Azalea", "Red" },
        new [] { "293432", "Aztec", "Green" },
        new [] { "F0FFFF", "Azure", "Blue" },
        new [] { "6FFFFF", "Baby Blue", "Blue" },
        new [] { "25597F", "Bahama Blue", "Blue" },
        new [] { "A9C01C", "Bahia", "Green" },
        new [] { "5C3317", "Baker's Chocolate", "Brown" },
        new [] { "849CA9", "Bali Hai", "Blue" },
        new [] { "3C3D3E", "Baltic Sea", "Grey" },
        new [] { "FBE7B2", "Banana Mania", "Yellow" },
        new [] { "878466", "Bandicoot", "Green" },
        new [] { "D2C61F", "Barberry", "Green" },
        new [] { "B6935C", "Barley Corn", "Yellow" },
        new [] { "F7E5B7", "Barley White", "Yellow" },
        new [] { "452E39", "Barossa", "Violet" },
        new [] { "2C2C32", "Bastille", "Blue" },
        new [] { "51574F", "Battleship Grey", "Grey" },
        new [] { "7BB18D", "Bay Leaf", "Green" },
        new [] { "353E64", "Bay Of Many", "Blue" },
        new [] { "8F7777", "Bazaar", "Brown" },
        new [] { "EBB9B3", "Beauty Bush", "Red" },
        new [] { "926F5B", "Beaver", "Brown" },
        new [] { "E9D7AB", "Beeswax", "Yellow" },
        new [] { "F5F5DC", "Beige", "Brown" },
        new [] { "86D2C1", "Bermuda", "Green" },
        new [] { "6F8C9F", "Bermuda Grey", "Blue" },
        new [] { "BCBFA8", "Beryl Green", "Green" },
        new [] { "F4EFE0", "Bianca", "Yellow" },
        new [] { "334046", "Big Stone", "Blue" },
        new [] { "3E8027", "Bilbao", "Green" },
        new [] { "AE99D2", "Biloba Flower", "Violet" },
        new [] { "3F3726", "Birch", "Yellow" },
        new [] { "D0C117", "Bird Flower", "Green" },
        new [] { "2F3C53", "Biscay", "Blue" },
        new [] { "486C7A", "Bismark", "Blue" },
        new [] { "B5AC94", "Bison Hide", "Yellow" },
        new [] { "FFE4C4", "Bisque", "Brown" },
        new [] { "3D2B1F", "Bistre", "Brown" },
        new [] { "88896C", "Bitter", "Green" },
        new [] { "D2DB32", "Bitter Lemon", "Green" },
        new [] { "FE6F5E", "Bittersweet", "Orange" },
        new [] { "E7D2C8", "Bizarre", "Orange" },
        new [] { "000000", "Black", "Black" },
        new [] { "232E26", "Black Bean", "Green" },
        new [] { "2C3227", "Black Forest", "Green" },
        new [] { "E0DED7", "Black Haze", "Grey" },
        new [] { "332C22", "Black Magic", "Brown" },
        new [] { "383740", "Black Marlin", "Blue" },
        new [] { "1E272C", "Black Pearl", "Blue" },
        new [] { "2C2D3C", "Black Rock", "Blue" },
        new [] { "532934", "Black Rose", "Red" },
        new [] { "24252B", "Black Russian", "Grey" },
        new [] { "E5E6DF", "Black Squeeze", "Grey" },
        new [] { "E5E4DB", "Black White", "Grey" },
        new [] { "43182F", "Blackberry", "Violet" },
        new [] { "2E183B", "Blackcurrant", "Violet" },
        new [] { "D9D0C1", "Blanc", "Yellow" },
        new [] { "FFEBCD", "Blanched Almond", "Brown" },
        new [] { "EBE1CE", "Bleach White", "Yellow" },
        new [] { "A3E3ED", "Blizzard Blue", "Blue" },
        new [] { "DFB1B6", "Blossom", "Red" },
        new [] { "0000FF", "Blue", "Blue" },
        new [] { "62777E", "Blue Bayoux", "Blue" },
        new [] { "9999CC", "Blue Bell", "Blue" },
        new [] { "E3D6E9", "Blue Chalk", "Violet" },
        new [] { "262B2F", "Blue Charcoal", "Blue" },
        new [] { "408F90", "Blue Chill", "Green" },
        new [] { "4B2D72", "Blue Diamond", "Violet" },
        new [] { "35514F", "Blue Dianne", "Green" },
        new [] { "4B3C8E", "Blue Gem", "Violet" },
        new [] { "BDBACE", "Blue Haze", "Violet" },
        new [] { "00626F", "Blue Lagoon", "Green" },
        new [] { "6A5BB1", "Blue Marguerite", "Violet" },
        new [] { "D8F0D2", "Blue Romance", "Green" },
        new [] { "78857A", "Blue Smoke", "Green" },
        new [] { "166461", "Blue Stone", "Green" },
        new [] { "8A2BE2", "Blue Violet", "Violet" },
        new [] { "1E3442", "Blue Whale", "Blue" },
        new [] { "3C4354", "Blue Zodiac", "Blue" },
        new [] { "305C71", "Blumine", "Blue" },
        new [] { "B55067", "Blush", "Red" },
        new [] { "2A2725", "Bokara Grey", "Grey" },
        new [] { "79443B", "Bole", "Brown" },
        new [] { "AEAEAD", "Bombay", "Grey" },
        new [] { "DFD7D2", "Bon Jour", "Grey" },
        new [] { "0095B6", "Bondi Blue", "Blue" },
        new [] { "DBC2AB", "Bone", "Orange" },
        new [] { "4C1C24", "Bordeaux", "Red" },
        new [] { "4C3D4E", "Bossanova", "Violet" },
        new [] { "438EAC", "Boston Blue", "Blue" },
        new [] { "92ACB4", "Botticelli", "Blue" },
        new [] { "254636", "Bottle Green", "Green" },
        new [] { "7C817C", "Boulder", "Grey" },
        new [] { "A78199", "Bouquet", "Violet" },
        new [] { "AF6C3E", "Bourbon", "Orange" },
        new [] { "5B3D27", "Bracken", "Brown" },
        new [] { "DCB68A", "Brandy", "Orange" },
        new [] { "C07C40", "Brandy Punch", "Orange" },
        new [] { "B6857A", "Brandy Rose", "Red" },
        new [] { "B5A642", "Brass", "Yellow" },
        new [] { "517B78", "Breaker Bay", "Green" },
        new [] { "C62D42", "Brick Red", "Red" },
        new [] { "F8EBDD", "Bridal Heath", "Orange" },
        new [] { "FAE6DF", "Bridesmaid", "Orange" },
        new [] { "66FF00", "Bright Green", "Green" },
        new [] { "57595D", "Bright Grey", "Grey" },
        new [] { "922A31", "Bright Red", "Red" },
        new [] { "ECBD2C", "Bright Sun", "Yellow" },
        new [] { "08E8DE", "Bright Turquoise", "Blue" },
        new [] { "FF55A3", "Brilliant Rose", "Red" },
        new [] { "FB607F", "Brink Pink", "Red" },
        new [] { "004225", "British Racing Green", "Green" },
        new [] { "A79781", "Bronco", "Brown" },
        new [] { "CD7F32", "Bronze", "Brown" },
        new [] { "584C25", "Bronze Olive", "Yellow" },
        new [] { "434C28", "Bronzetone", "Yellow" },
        new [] { "EECC24", "Broom", "Yellow" },
        new [] { "A52A2A", "Brown", "Brown" },
        new [] { "53331E", "Brown Bramble", "Brown" },
        new [] { "594537", "Brown Derby", "Brown" },
        new [] { "3C241B", "Brown Pod", "Brown" },
        new [] { "E6F2EA", "Bubbles", "Green" },
        new [] { "6E5150", "Buccaneer", "Red" },
        new [] { "A5A88F", "Bud", "Green" },
        new [] { "BC9B1B", "Buddha Gold", "Yellow" },
        new [] { "F0DC82", "Buff", "Yellow" },
        new [] { "482427", "Bulgarian Rose", "Red" },
        new [] { "75442B", "Bull Shot", "Orange" },
        new [] { "292C2F", "Bunker", "Grey" },
        new [] { "2B3449", "Bunting", "Blue" },
        new [] { "800020", "Burgundy", "Red" },
        new [] { "DEB887", "Burly Wood", "Brown" },
        new [] { "234537", "Burnham", "Green" },
        new [] { "D08363", "Burning Sand", "Orange" },
        new [] { "582124", "Burnt Crimson", "Red" },
        new [] { "FF7034", "Burnt Orange", "Orange" },
        new [] { "E97451", "Burnt Sienna", "Brown" },
        new [] { "8A3324", "Burnt Umber", "Brown" },
        new [] { "DA9429", "Buttercup", "Yellow" },
        new [] { "9D702E", "Buttered Rum", "Yellow" },
        new [] { "68578C", "Butterfly Bush", "Violet" },
        new [] { "F6E0A4", "Buttermilk", "Yellow" },
        new [] { "F1EBDA", "Buttery White", "Yellow" },
        new [] { "4A2E32", "Cab Sav", "Red" },
        new [] { "CD526C", "Cabaret", "Red" },
        new [] { "4C5544", "Cabbage Pont", "Green" },
        new [] { "5B6F55", "Cactus", "Green" },
        new [] { "5F9EA0", "Cadet Blue", "Blue" },
        new [] { "984961", "Cadillac", "Red" },
        new [] { "6A4928", "Cafe Royale", "Brown" },
        new [] { "D5B185", "Calico", "Brown" },
        new [] { "E98C3A", "California", "Orange" },
        new [] { "3D7188", "Calypso", "Blue" },
        new [] { "206937", "Camarone", "Green" },
        new [] { "803A4B", "Camelot", "Red" },
        new [] { "CCA483", "Cameo", "Brown" },
        new [] { "4F4D32", "Camouflage", "Yellow" },
        new [] { "78866B", "Camouflage Green", "Green" },
        new [] { "D08A9B", "Can Can", "Red" },
        new [] { "FFFF99", "Canary", "Yellow" },
        new [] { "8E5164", "Cannon Pink", "Red" },
        new [] { "4E5552", "Cape Cod", "Grey" },
        new [] { "FEE0A5", "Cape Honey", "Yellow" },
        new [] { "75482F", "Cape Palliser", "Orange" },
        new [] { "AFC182", "Caper", "Green" },
        new [] { "592720", "Caput Mortuum", "Brown" },
        new [] { "FFD59A", "Caramel", "Yellow" },
        new [] { "EBE5D5", "Cararra", "Green" },
        new [] { "1B3427", "Cardin Green", "Green" },
        new [] { "C41E3A", "Cardinal", "Red" },
        new [] { "C99AA0", "Careys Pink", "Red" },
        new [] { "00CC99", "Caribbean Green", "Green" },
        new [] { "E68095", "Carissma", "Red" },
        new [] { "F5F9CB", "Carla", "Green" },
        new [] { "960018", "Carmine", "Red" },
        new [] { "5B3A24", "Carnaby Tan", "Brown" },
        new [] { "FFA6C9", "Carnation Pink", "Red" },
        new [] { "F8DBE0", "Carousel Pink", "Red" },
        new [] { "ED9121", "Carrot Orange", "Orange" },
        new [] { "F0B253", "Casablanca", "Yellow" },
        new [] { "3F545A", "Casal", "Blue" },
        new [] { "8CA8A0", "Cascade", "Green" },
        new [] { "D1B399", "Cashmere", "Brown" },
        new [] { "AAB5B8", "Casper", "Blue" },
        new [] { "44232F", "Castro", "Red" },
        new [] { "273C5A", "Catalina Blue", "Blue" },
        new [] { "E0E4DC", "Catskill White", "Grey" },
        new [] { "E0B8B1", "Cavern Pink", "Red" },
        new [] { "9271A7", "Ce Soir", "Violet" },
        new [] { "463430", "Cedar", "Brown" },
        new [] { "ACE1AF", "Celadon", "Green" },
        new [] { "B4C04C", "Celery", "Green" },
        new [] { "D2D2C0", "Celeste", "Green" },
        new [] { "3A4E5F", "Cello", "Blue" },
        new [] { "2B3F36", "Celtic", "Green" },
        new [] { "857158", "Cement", "Brown" },
        new [] { "DE3163", "Cerise", "Violet" },
        new [] { "007BA7", "Cerulean", "Blue" },
        new [] { "2A52BE", "Cerulean Blue", "Blue" },
        new [] { "FDE9E0", "Chablis", "Red" },
        new [] { "5A6E41", "Chalet Green", "Green" },
        new [] { "DFC281", "Chalky", "Yellow" },
        new [] { "475877", "Chambray", "Blue" },
        new [] { "E8CD9A", "Chamois", "Yellow" },
        new [] { "EED9B6", "Champagne", "Yellow" },
        new [] { "EDB8C7", "Chantilly", "Red" },
        new [] { "394043", "Charade", "Blue" },
        new [] { "464646", "Charcoal", "Grey" },
        new [] { "F8EADF", "Chardon", "Orange" },
        new [] { "FFC878", "Chardonnay", "Yellow" },
        new [] { "A4DCE6", "Charlotte", "Blue" },
        new [] { "D0748B", "Charm", "Red" },
        new [] { "7FFF00", "Chartreuse", "Green" },
        new [] { "DFFF00", "Chartreuse Yellow", "Yellow" },
        new [] { "419F59", "Chateau Green", "Green" },
        new [] { "B3ABB6", "Chatelle", "Violet" },
        new [] { "2C5971", "Chathams Blue", "Blue" },
        new [] { "88A95B", "Chelsea Cucumber", "Green" },
        new [] { "95532F", "Chelsea Gem", "Orange" },
        new [] { "DEC371", "Chenin", "Yellow" },
        new [] { "F5CD82", "Cherokee", "Yellow" },
        new [] { "372D52", "Cherry Pie", "Violet" },
        new [] { "F5D7DC", "Cherub", "Red" },
        new [] { "B94E48", "Chestnut", "Brown" },
        new [] { "666FB4", "Chetwode Blue", "Blue" },
        new [] { "5B5D56", "Chicago", "Grey" },
        new [] { "F0F5BB", "Chiffon", "Green" },
        new [] { "D05E34", "Chilean Fire", "Orange" },
        new [] { "F9F7DE", "Chilean Heath", "Green" },
        new [] { "FBF3D3", "China Ivory", "Green" },
        new [] { "B8AD8A", "Chino", "Yellow" },
        new [] { "9DD3A8", "Chinook", "Green" },
        new [] { "D2691E", "Chocolate", "Brown" },
        new [] { "382161", "Christalle", "Violet" },
        new [] { "71A91D", "Christi", "Green" },
        new [] { "BF652E", "Christine", "Orange" },
        new [] { "CAC7B7", "Chrome White", "Green" },
        new [] { "7D4E38", "Cigar", "Brown" },
        new [] { "242A2E", "Cinder", "Grey" },
        new [] { "FBD7CC", "Cinderella", "Red" },
        new [] { "E34234", "Cinnabar", "Red" },
        new [] { "5D3B2E", "Cioccolato", "Brown" },
        new [] { "8E9A21", "Citron", "Green" },
        new [] { "9FB70A", "Citrus", "Green" },
        new [] { "D2B3A9", "Clam Shell", "Orange" },
        new [] { "6E2233", "Claret", "Red" },
        new [] { "F4C8DB", "Classic Rose", "Violet" },
        new [] { "897E59", "Clay Creek", "Yellow" },
        new [] { "DFEFEA", "Clear Day", "Green" },
        new [] { "463623", "Clinker", "Brown" },
        new [] { "C2BCB1", "Cloud", "Yellow" },
        new [] { "353E4F", "Cloud Burst", "Blue" },
        new [] { "B0A99F", "Cloudy", "Brown" },
        new [] { "47562F", "Clover", "Green" },
        new [] { "0047AB", "Cobalt", "Blue" },
        new [] { "4F3835", "Cocoa Bean", "Red" },
        new [] { "35281E", "Cocoa Brown", "Brown" },
        new [] { "E1DABB", "Coconut Cream", "Green" },
        new [] { "2D3032", "Cod Grey", "Grey" },
        new [] { "726751", "Coffee", "Yellow" },
        new [] { "362D26", "Coffee Bean", "Brown" },
        new [] { "9A463D", "Cognac", "Red" },
        new [] { "3C2F23", "Cola", "Brown" },
        new [] { "9D8ABF", "Cold Purple", "Violet" },
        new [] { "CAB5B2", "Cold Turkey", "Red" },
        new [] { "9BDDFF", "Columbia Blue", "Blue" },
        new [] { "636373", "Comet", "Blue" },
        new [] { "4C785C", "Como", "Green" },
        new [] { "A0B1AE", "Conch", "Green" },
        new [] { "827F79", "Concord", "Grey" },
        new [] { "D2D1CD", "Concrete", "Grey" },
        new [] { "DDCB46", "Confetti", "Green" },
        new [] { "654D49", "Congo Brown", "Brown" },
        new [] { "B1DD52", "Conifer", "Green" },
        new [] { "C16F68", "Contessa", "Red" },
        new [] { "DA8A67", "Copper", "Red" },
        new [] { "77422C", "Copper Canyon", "Orange" },
        new [] { "996666", "Copper Rose", "Violet" },
        new [] { "95524C", "Copper Rust", "Red" },
        new [] { "FF7F50", "Coral", "Orange" },
        new [] { "F5D0C9", "Coral Candy", "Red" },
        new [] { "FF4040", "Coral Red", "Red" },
        new [] { "AB6E67", "Coral Tree", "Red" },
        new [] { "404D49", "Corduroy", "Green" },
        new [] { "BBB58D", "Coriander", "Green" },
        new [] { "5A4C42", "Cork", "Brown" },
        new [] { "FBEC5D", "Corn", "Yellow" },
        new [] { "F8F3C4", "Corn Field", "Green" },
        new [] { "42426F", "Corn Flower Blue", "Blue" },
        new [] { "8D702A", "Corn Harvest", "Yellow" },
        new [] { "FFF8DC", "Corn Silk", "Yellow" },
        new [] { "93CCEA", "Cornflower", "Blue" },
        new [] { "6495ED", "Cornflower Blue", "Blue" },
        new [] { "E9BA81", "Corvette", "Orange" },
        new [] { "794D60", "Cosmic", "Violet" },
        new [] { "E1F8E7", "Cosmic Latte", "White" },
        new [] { "FCD5CF", "Cosmos", "Red" },
        new [] { "625D2A", "Costa Del Sol", "Green" },
        new [] { "FFB7D5", "Cotton Candy", "Red" },
        new [] { "BFBAAF", "Cotton Seed", "Yellow" },
        new [] { "1B4B35", "County Green", "Green" },
        new [] { "443736", "Cowboy", "Brown" },
        new [] { "87382F", "Crab Apple", "Red" },
        new [] { "A65648", "Crail", "Red" },
        new [] { "DB5079", "Cranberry", "Red" },
        new [] { "4D3E3C", "Crater Brown", "Brown" },
        new [] { "FFFDD0", "Cream", "White" },
        new [] { "FFE39B", "Cream Brulee", "Yellow" },
        new [] { "EEC051", "Cream Can", "Yellow" },
        new [] { "393227", "Creole", "Brown" },
        new [] { "77712B", "Crete", "Green" },
        new [] { "DC143C", "Crimson", "Red" },
        new [] { "706950", "Crocodile", "Yellow" },
        new [] { "763C33", "Crown Of Thorns", "Red" },
        new [] { "B4E2D5", "Cruise", "Green" },
        new [] { "165B31", "Crusoe", "Green" },
        new [] { "F38653", "Crusta", "Orange" },
        new [] { "784430", "Cumin", "Orange" },
        new [] { "F5F4C1", "Cumulus", "Green" },
        new [] { "F5B2C5", "Cupid", "Red" },
        new [] { "3D85B8", "Curious Blue", "Blue" },
        new [] { "5C8173", "Cutty Sark", "Green" },
        new [] { "0F4645", "Cyprus", "Green" },
        new [] { "EDD2A4", "Dairy Cream", "Yellow" },
        new [] { "5B3E90", "Daisy Bush", "Violet" },
        new [] { "664A2D", "Dallas", "Brown" },
        new [] { "FED85D", "Dandelion", "Yellow" },
        new [] { "5B89C0", "Danube", "Blue" },
        new [] { "00008B", "Dark Blue", "Blue" },
        new [] { "654321", "Dark Brown", "Brown" },
        new [] { "08457E", "Dark Cerulean", "Blue" },
        new [] { "986960", "Dark Chestnut", "Red" },
        new [] { "CD5B45", "Dark Coral", "Orange" },
        new [] { "008B8B", "Dark Cyan", "Green" },
        new [] { "B8860B", "Dark Goldenrod", "Yellow" },
        new [] { "A9A9A9", "Dark Gray", "Grey" },
        new [] { "013220", "Dark Green", "Green" },
        new [] { "4A766E", "Dark Green Copper", "Green" },
        new [] { "BDB76B", "Dark Khaki", "Yellow" },
        new [] { "8B008B", "Dark Magenta", "Violet" },
        new [] { "556B2F", "Dark Olive Green", "Green" },
        new [] { "FF8C00", "Dark Orange", "Orange" },
        new [] { "9932CC", "Dark Orchid", "Violet" },
        new [] { "03C03C", "Dark Pastel Green", "Green" },
        new [] { "E75480", "Dark Pink", "Red" },
        new [] { "871F78", "Dark Purple", "Violet" },
        new [] { "8B0000", "Dark Red", "Red" },
        new [] { "45362B", "Dark Rum", "Brown" },
        new [] { "E9967A", "Dark Salmon", "Orange" },
        new [] { "8FBC8F", "Dark Sea Green", "Green" },
        new [] { "465352", "Dark Slate", "Green" },
        new [] { "483D8B", "Dark Slate Blue", "Blue" },
        new [] { "2F4F4F", "Dark Slate Grey", "Grey" },
        new [] { "177245", "Dark Spring Green", "Green" },
        new [] { "97694F", "Dark Tan", "Brown" },
        new [] { "FFA812", "Dark Tangerine", "Orange" },
        new [] { "00CED1", "Dark Turquoise", "Blue" },
        new [] { "9400D3", "Dark Violet", "Violet" },
        new [] { "855E42", "Dark Wood", "Brown" },
        new [] { "788878", "Davy's Grey", "Grey" },
        new [] { "9F9D91", "Dawn", "Green" },
        new [] { "E6D6CD", "Dawn Pink", "Orange" },
        new [] { "85CA87", "De York", "Green" },
        new [] { "CCCF82", "Deco", "Green" },
        new [] { "E36F8A", "Deep Blush", "Red" },
        new [] { "51412D", "Deep Bronze", "Brown" },
        new [] { "DA3287", "Deep Cerise", "Violet" },
        new [] { "193925", "Deep Fir", "Green" },
        new [] { "343467", "Deep Koamaru", "Violet" },
        new [] { "9955BB", "Deep Lilac", "Violet" },
        new [] { "CC00CC", "Deep Magenta", "Violet" },
        new [] { "FF1493", "Deep Pink", "Red" },
        new [] { "167E65", "Deep Sea", "Green" },
        new [] { "00BFFF", "Deep Sky Blue", "Blue" },
        new [] { "19443C", "Deep Teal", "Green" },
        new [] { "B5998E", "Del Rio", "Brown" },
        new [] { "486531", "Dell", "Green" },
        new [] { "999B95", "Delta", "Grey" },
        new [] { "8272A4", "Deluge", "Violet" },
        new [] { "1560BD", "Denim", "Blue" },
        new [] { "F9E4C6", "Derby", "Yellow" },
        new [] { "A15F3B", "Desert", "Orange" },
        new [] { "EDC9AF", "Desert Sand", "Brown" },
        new [] { "EDE7E0", "Desert Storm", "Grey" },
        new [] { "E7F2E9", "Dew", "Green" },
        new [] { "322C2B", "Diesel", "Grey" },
        new [] { "696969", "Dim Gray", "Grey" },
        new [] { "607C47", "Dingley", "Green" },
        new [] { "892D4F", "Disco", "Red" },
        new [] { "CD8431", "Dixie", "Yellow" },
        new [] { "1E90FF", "Dodger Blue", "Blue" },
        new [] { "F5F171", "Dolly", "Green" },
        new [] { "6A6873", "Dolphin", "Violet" },
        new [] { "6C5B4C", "Domino", "Brown" },
        new [] { "5A4F51", "Don Juan", "Brown" },
        new [] { "816E5C", "Donkey Brown", "Brown" },
        new [] { "6E5F56", "Dorado", "Brown" },
        new [] { "E4CF99", "Double Colonial White", "Yellow" },
        new [] { "E9DCBE", "Double Pearl Lusta", "Yellow" },
        new [] { "D2C3A3", "Double Spanish White", "Yellow" },
        new [] { "777672", "Dove Grey", "Grey" },
        new [] { "6FD2BE", "Downy", "Green" },
        new [] { "FBEB9B", "Drover", "Yellow" },
        new [] { "514F4A", "Dune", "Grey" },
        new [] { "E5CAC0", "Dust Storm", "Orange" },
        new [] { "AC9B9B", "Dusty Grey", "Grey" },
        new [] { "F0DFBB", "Dutch White", "Yellow" },
        new [] { "B0AC94", "Eagle", "Green" },
        new [] { "B8A722", "Earls Green", "Green" },
        new [] { "FBF2DB", "Early Dawn", "Yellow" },
        new [] { "47526E", "East Bay", "Blue" },
        new [] { "AA8CBC", "East Side", "Violet" },
        new [] { "00879F", "Eastern Blue", "Blue" },
        new [] { "E6D8D4", "Ebb", "Red" },
        new [] { "313337", "Ebony", "Grey" },
        new [] { "323438", "Ebony Clay", "Grey" },
        new [] { "A4AFCD", "Echo Blue", "Blue" },
        new [] { "3F3939", "Eclipse", "Grey" },
        new [] { "C2B280", "Ecru", "Brown" },
        new [] { "D6D1C0", "Ecru White", "Green" },
        new [] { "C96138", "Ecstasy", "Orange" },
        new [] { "266255", "Eden", "Green" },
        new [] { "C1D8C5", "Edgewater", "Green" },
        new [] { "97A49A", "Edward", "Green" },
        new [] { "F9E4C5", "Egg Sour", "Yellow" },
        new [] { "990066", "Eggplant", "Violet" },
        new [] { "1034A6", "Egyptian Blue", "Blue" },
        new [] { "39392C", "El Paso", "Green" },
        new [] { "8F4E45", "El Salva", "Red" },
        new [] { "7DF9FF", "Electric Blue", "Blue" },
        new [] { "6600FF", "Electric Indigo", "Violet" },
        new [] { "CCFF00", "Electric Lime", "Green" },
        new [] { "BF00FF", "Electric Purple", "Violet" },
        new [] { "243640", "Elephant", "Blue" },
        new [] { "1B8A6B", "Elf Green", "Green" },
        new [] { "297B76", "Elm", "Green" },
        new [] { "50C878", "Emerald", "Green" },
        new [] { "6E3974", "Eminence", "Violet" },
        new [] { "50494A", "Emperor", "Grey" },
        new [] { "7C7173", "Empress", "Grey" },
        new [] { "29598B", "Endeavour", "Blue" },
        new [] { "F5D752", "Energy Yellow", "Yellow" },
        new [] { "274234", "English Holly", "Green" },
        new [] { "8BA58F", "Envy", "Green" },
        new [] { "DAB160", "Equator", "Yellow" },
        new [] { "4E312D", "Espresso", "Red" },
        new [] { "2D2F28", "Eternity", "Green" },
        new [] { "329760", "Eucalyptus", "Green" },
        new [] { "CDA59C", "Eunry", "Red" },
        new [] { "26604F", "Evening Sea", "Green" },
        new [] { "264334", "Everglade", "Green" },
        new [] { "F3E5DC", "Fair Pink", "Orange" },
        new [] { "6E5A5B", "Falcon", "Brown" },
        new [] { "C19A6B", "Fallow", "Brown" },
        new [] { "801818", "Falu Red", "Red" },
        new [] { "F2E6DD", "Fantasy", "Orange" },
        new [] { "625665", "Fedora", "Violet" },
        new [] { "A5D785", "Feijoa", "Green" },
        new [] { "4D5D53", "Feldgrau", "Grey" },
        new [] { "D19275", "Feldspar", "Red" },
        new [] { "63B76C", "Fern", "Green" },
        new [] { "4F7942", "Fern Green", "Green" },
        new [] { "876A68", "Ferra", "Brown" },
        new [] { "EACC4A", "Festival", "Yellow" },
        new [] { "DBE0D0", "Feta", "Green" },
        new [] { "B1592F", "Fiery Orange", "Orange" },
        new [] { "636F22", "Fiji Green", "Green" },
        new [] { "75785A", "Finch", "Green" },
        new [] { "61755B", "Finlandia", "Green" },
        new [] { "694554", "Finn", "Violet" },
        new [] { "4B5A62", "Fiord", "Blue" },
        new [] { "8F3F2A", "Fire", "Orange" },
        new [] { "B22222", "Fire Brick", "Red" },
        new [] { "E09842", "Fire Bush", "Yellow" },
        new [] { "CE1620", "Fire Engine Red", "Red" },
        new [] { "314643", "Firefly", "Green" },
        new [] { "BE5C48", "Flame Pea", "Orange" },
        new [] { "86282E", "Flame Red", "Red" },
        new [] { "EA8645", "Flamenco", "Orange" },
        new [] { "E1634F", "Flamingo", "Orange" },
        new [] { "EEDC82", "Flax", "Yellow" },
        new [] { "716E61", "Flint", "Green" },
        new [] { "7A2E4D", "Flirt", "Red" },
        new [] { "FFFAF0", "Floral White", "White" },
        new [] { "D0EAE8", "Foam", "Green" },
        new [] { "D5C7E8", "Fog", "Violet" },
        new [] { "A7A69D", "Foggy Grey", "Grey" },
        new [] { "228B22", "Forest Green", "Green" },
        new [] { "FDEFDB", "Forget Me Not", "Yellow" },
        new [] { "65ADB2", "Fountain Blue", "Blue" },
        new [] { "FFD7A0", "Frangipani", "Yellow" },
        new [] { "029D74", "Free Speech Aquamarine", "Green" },
        new [] { "4156C5", "Free Speech Blue", "Blue" },
        new [] { "09F911", "Free Speech Green", "Green" },
        new [] { "E35BD8", "Free Speech Magenta", "Red" },
        new [] { "C00000", "Free Speech Red", "Red" },
        new [] { "BFBDC1", "French Grey", "Grey" },
        new [] { "DEB7D9", "French Lilac", "Violet" },
        new [] { "A4D2E0", "French Pass", "Blue" },
        new [] { "F64A8A", "French Rose", "Red" },
        new [] { "86837A", "Friar Grey", "Grey" },
        new [] { "B4E1BB", "Fringy Flower", "Green" },
        new [] { "E56D75", "Froly", "Red" },
        new [] { "E1E4C5", "Frost", "Green" },
        new [] { "E2F2E4", "Frosted Mint", "Green" },
        new [] { "DBE5D2", "Frostee", "Green" },
        new [] { "4BA351", "Fruit Salad", "Green" },
        new [] { "C154C1", "Fuchsia", "Violet" },
        new [] { "FF77FF", "Fuchsia Pink", "Red" },
        new [] { "C2D62E", "Fuego", "Green" },
        new [] { "D19033", "Fuel Yellow", "Yellow" },
        new [] { "335083", "Fun Blue", "Blue" },
        new [] { "15633D", "Fun Green", "Green" },
        new [] { "3C3B3C", "Fuscous Grey", "Grey" },
        new [] { "C45655", "Fuzzy Wuzzy Brown", "Brown" },
        new [] { "2C4641", "Gable Green", "Green" },
        new [] { "DCDCDC", "Gainsboro", "White" },
        new [] { "DCD7D1", "Gallery", "Grey" },
        new [] { "D8A723", "Galliano", "Yellow" },
        new [] { "E49B0F", "Gamboge", "Yellow" },
        new [] { "C5832E", "Geebung", "Yellow" },
        new [] { "31796D", "Genoa", "Green" },
        new [] { "E77B75", "Geraldine", "Red" },
        new [] { "CBD0CF", "Geyser", "Grey" },
        new [] { "C0BFC7", "Ghost", "Blue" },
        new [] { "F8F8FF", "Ghost White", "White" },
        new [] { "564786", "Gigas", "Violet" },
        new [] { "B9AD61", "Gimblet", "Green" },
        new [] { "D9DFCD", "Gin", "Green" },
        new [] { "F8EACA", "Gin Fizz", "Yellow" },
        new [] { "EBD4AE", "Givry", "Yellow" },
        new [] { "78B1BF", "Glacier", "Blue" },
        new [] { "5F8151", "Glade Green", "Green" },
        new [] { "786E4C", "Go Ben", "Yellow" },
        new [] { "34533D", "Goblin", "Green" },
        new [] { "FFD700", "Gold", "Yellow" },
        new [] { "D56C30", "Gold Drop", "Orange" },
        new [] { "E2B227", "Gold Tips", "Yellow" },
        new [] { "CA8136", "Golden Bell", "Orange" },
        new [] { "996515", "Golden Brown", "Brown" },
        new [] { "F1CC2B", "Golden Dream", "Yellow" },
        new [] { "EBDE31", "Golden Fizz", "Green" },
        new [] { "F9D77E", "Golden Glow", "Yellow" },
        new [] { "FCC200", "Golden Poppy", "Yellow" },
        new [] { "EACE6A", "Golden Sand", "Yellow" },
        new [] { "FFC152", "Golden Tainoi", "Yellow" },
        new [] { "FFDF00", "Golden Yellow", "Yellow" },
        new [] { "DBDB70", "Goldenrod", "Yellow" },
        new [] { "373332", "Gondola", "Grey" },
        new [] { "29332B", "Gordons Green", "Green" },
        new [] { "FDE336", "Gorse", "Green" },
        new [] { "399F86", "Gossamer", "Green" },
        new [] { "9FD385", "Gossip", "Green" },
        new [] { "698890", "Gothic", "Blue" },
        new [] { "51559B", "Governor Bay", "Blue" },
        new [] { "CAB8A2", "Grain Brown", "Yellow" },
        new [] { "FFCD73", "Grandis", "Yellow" },
        new [] { "8B8265", "Granite Green", "Yellow" },
        new [] { "C5E7CD", "Granny Apple", "Green" },
        new [] { "7B948C", "Granny Smith", "Green" },
        new [] { "9DE093", "Granny Smith Apple", "Green" },
        new [] { "413D4B", "Grape", "Violet" },
        new [] { "383428", "Graphite", "Yellow" },
        new [] { "4A4B46", "Gravel", "Grey" },
        new [] { "008000", "Green", "Green" },
        new [] { "3E6334", "Green House", "Green" },
        new [] { "393D2A", "Green Kelp", "Green" },
        new [] { "526B2D", "Green Leaf", "Green" },
        new [] { "BFC298", "Green Mist", "Green" },
        new [] { "266242", "Green Pea", "Green" },
        new [] { "9CA664", "Green Smoke", "Green" },
        new [] { "A9AF99", "Green Spring", "Green" },
        new [] { "23414E", "Green Vogue", "Blue" },
        new [] { "2C2D24", "Green Waterloo", "Green" },
        new [] { "DEDDCB", "Green White", "Green" },
        new [] { "ADFF2F", "Green Yellow", "Green" },
        new [] { "C14D36", "Grenadier", "Orange" },
        new [] { "808080", "Grey", "Grey" },
        new [] { "9FA3A7", "Grey Chateau", "Grey" },
        new [] { "BDBAAE", "Grey Nickel", "Green" },
        new [] { "D1D3CC", "Grey Nurse", "Grey" },
        new [] { "A19A7F", "Grey Olive", "Yellow" },
        new [] { "9391A0", "Grey Suit", "Blue" },
        new [] { "465945", "Grey-Asparagus", "Green" },
        new [] { "952E31", "Guardsman Red", "Red" },
        new [] { "343F5C", "Gulf Blue", "Blue" },
        new [] { "74B2A8", "Gulf Stream", "Green" },
        new [] { "A4ADB0", "Gull Grey", "Grey" },
        new [] { "ACC9B2", "Gum Leaf", "Green" },
        new [] { "718F8A", "Gumbo", "Green" },
        new [] { "484753", "Gun Powder", "Violet" },
        new [] { "2C3539", "Gunmetal", "Blue" },
        new [] { "7A7C76", "Gunsmoke", "Grey" },
        new [] { "989171", "Gurkha", "Green" },
        new [] { "9E8022", "Hacienda", "Yellow" },
        new [] { "633528", "Hairy Heath", "Brown" },
        new [] { "2C2A35", "Haiti", "Violet" },
        new [] { "EDE7C8", "Half And Half", "Green" },
        new [] { "558F93", "Half Baked", "Blue" },
        new [] { "F2E5BF", "Half Colonial White", "Yellow" },
        new [] { "FBF0D6", "Half Dutch White", "Yellow" },
        new [] { "F1EAD7", "Half Pearl Lusta", "Yellow" },
        new [] { "E6DBC7", "Half Spanish White", "Yellow" },
        new [] { "E8D4A2", "Hampton", "Yellow" },
        new [] { "5218FA", "Han Purple", "Violet" },
        new [] { "3FFF00", "Harlequin", "Green" },
        new [] { "C93413", "Harley Davidson Orange", "Orange" },
        new [] { "CBCEC0", "Harp", "Green" },
        new [] { "EAB76A", "Harvest Gold", "Yellow" },
        new [] { "3B2B2C", "Havana", "Brown" },
        new [] { "5784C1", "Havelock Blue", "Blue" },
        new [] { "99522B", "Hawaiian Tan", "Orange" },
        new [] { "D2DAED", "Hawkes Blue", "Blue" },
        new [] { "4F2A2C", "Heath", "Red" },
        new [] { "AEBBC1", "Heather", "Blue" },
        new [] { "948C7E", "Heathered Grey", "Brown" },
        new [] { "46473E", "Heavy Metal", "Grey" },
        new [] { "DF73FF", "Heliotrope", "Violet" },
        new [] { "69684B", "Hemlock", "Yellow" },
        new [] { "987D73", "Hemp", "Brown" },
        new [] { "928C3C", "Highball", "Green" },
        new [] { "7A9461", "Highland", "Green" },
        new [] { "A7A07E", "Hillary", "Green" },
        new [] { "736330", "Himalaya", "Yellow" },
        new [] { "DFF1D6", "Hint Of Green", "Green" },
        new [] { "F5EFEB", "Hint Of Red", "Grey" },
        new [] { "F6F5D7", "Hint Of Yellow", "Green" },
        new [] { "49889A", "Hippie Blue", "Blue" },
        new [] { "608A5A", "Hippie Green", "Green" },
        new [] { "AB495C", "Hippie Pink", "Red" },
        new [] { "A1A9A8", "Hit Grey", "Grey" },
        new [] { "FDA470", "Hit Pink", "Orange" },
        new [] { "BB8E34", "Hokey Pokey", "Yellow" },
        new [] { "647D86", "Hoki", "Blue" },
        new [] { "25342B", "Holly", "Green" },
        new [] { "F400A1", "Hollywood Cerise", "Red" },
        new [] { "5C3C6D", "Honey Flower", "Violet" },
        new [] { "F0FFF0", "Honeydew", "White" },
        new [] { "E8ED69", "Honeysuckle", "Green" },
        new [] { "CD6D93", "Hopbush", "Violet" },
        new [] { "648894", "Horizon", "Blue" },
        new [] { "6D562C", "Horses Neck", "Yellow" },
        new [] { "815B28", "Hot Curry", "Yellow" },
        new [] { "FF00CC", "Hot Magenta", "Red" },
        new [] { "FF69B4", "Hot Pink", "Red" },
        new [] { "4E2E53", "Hot Purple", "Violet" },
        new [] { "A7752C", "Hot Toddy", "Yellow" },
        new [] { "CEEFE4", "Humming Bird", "Green" },
        new [] { "355E3B", "Hunter Green", "Green" },
        new [] { "8B7E77", "Hurricane", "Brown" },
        new [] { "B2994B", "Husk", "Yellow" },
        new [] { "AFE3D6", "Ice Cold", "Green" },
        new [] { "CAE1D9", "Iceberg", "Green" },
        new [] { "EF95AE", "Illusion", "Red" },
        new [] { "B0E313", "Inch Worm", "Green" },
        new [] { "CD5C5C", "Indian Red", "Red" },
        new [] { "4F301F", "Indian Tan", "Brown" },
        new [] { "4B0082", "Indigo", "Violet" },
        new [] { "9C5B34", "Indochine", "Orange" },
        new [] { "002FA7", "International Klein Blue", "Blue" },
        new [] { "FF4F00", "International Orange", "Orange" },
        new [] { "03B4C8", "Iris Blue", "Blue" },
        new [] { "62422B", "Irish Coffee", "Brown" },
        new [] { "CBCDCD", "Iron", "Grey" },
        new [] { "706E66", "Ironside Grey", "Grey" },
        new [] { "865040", "Ironstone", "Brown" },
        new [] { "009900", "Islamic Green", "Green" },
        new [] { "F8EDDB", "Island Spice", "Yellow" },
        new [] { "FFFFF0", "Ivory", "White" },
        new [] { "3D325D", "Jacarta", "Violet" },
        new [] { "413628", "Jacko Bean", "Brown" },
        new [] { "3D3F7D", "Jacksons Purple", "Violet" },
        new [] { "00A86B", "Jade", "Green" },
        new [] { "E27945", "Jaffa", "Orange" },
        new [] { "CAE7E2", "Jagged Ice", "Green" },
        new [] { "3F2E4C", "Jagger", "Violet" },
        new [] { "29292F", "Jaguar", "Blue" },
        new [] { "674834", "Jambalaya", "Brown" },
        new [] { "2F7532", "Japanese Laurel", "Green" },
        new [] { "CE7259", "Japonica", "Orange" },
        new [] { "259797", "Java", "Green" },
        new [] { "5F2C2F", "Jazz", "Red" },
        new [] { "A50B5E", "Jazzberry Jam", "Red" },
        new [] { "44798E", "Jelly Bean", "Blue" },
        new [] { "BBD0C9", "Jet Stream", "Green" },
        new [] { "136843", "Jewel", "Green" },
        new [] { "463D3E", "Jon", "Grey" },
        new [] { "EEF293", "Jonquil", "Green" },
        new [] { "7AAAE0", "Jordy Blue", "Blue" },
        new [] { "5D5346", "Judge Grey", "Brown" },
        new [] { "878785", "Jumbo", "Grey" },
        new [] { "29AB87", "Jungle Green", "Green" },
        new [] { "B0C4C4", "Jungle Mist", "Green" },
        new [] { "74918E", "Juniper", "Green" },
        new [] { "DCBFAC", "Just Right", "Orange" },
        new [] { "6C5E53", "Kabul", "Brown" },
        new [] { "245336", "Kaitoke Green", "Green" },
        new [] { "C5C3B0", "Kangaroo", "Green" },
        new [] { "2D2D24", "Karaka", "Green" },
        new [] { "FEDCC1", "Karry", "Orange" },
        new [] { "576D8E", "Kashmir Blue", "Blue" },
        new [] { "4CBB17", "Kelly Green", "Green" },
        new [] { "4D503C", "Kelp", "Green" },
        new [] { "6C322E", "Kenyan Copper", "Red" },
        new [] { "5FB69C", "Keppel", "Green" },
        new [] { "F0E68C", "Khaki", "Yellow" },
        new [] { "BFC0AB", "Kidnapper", "Green" },
        new [] { "3A3532", "Kilamanjaro", "Grey" },
        new [] { "49764F", "Killarney", "Green" },
        new [] { "695D87", "Kimberly", "Violet" },
        new [] { "583580", "Kingfisher Daisy", "Violet" },
        new [] { "E093AB", "Kobi", "Red" },
        new [] { "7B785A", "Kokoda", "Green" },
        new [] { "804E2C", "Korma", "Orange" },
        new [] { "FEB552", "Koromiko", "Yellow" },
        new [] { "F9D054", "Kournikova", "Yellow" },
        new [] { "428929", "La Palma", "Green" },
        new [] { "BAC00E", "La Rioja", "Green" },
        new [] { "C6DA36", "Las Palmas", "Green" },
        new [] { "C6A95E", "Laser", "Yellow" },
        new [] { "FFFF66", "Laser Lemon", "Yellow" },
        new [] { "6E8D71", "Laurel", "Green" },
        new [] { "E6E6FA", "Lavender", "Violet" },
        new [] { "CCCCFF", "Lavender Blue", "Blue" },
        new [] { "FFF0F5", "Lavender Blush", "Violet" },
        new [] { "BDBBD7", "Lavender Grey", "Grey" },
        new [] { "FBAED2", "Lavender Pink", "Red" },
        new [] { "FBA0E3", "Lavender Rose", "Red" },
        new [] { "7CFC00", "Lawn Green", "Green" },
        new [] { "906A54", "Leather", "Brown" },
        new [] { "FDE910", "Lemon", "Yellow" },
        new [] { "FFFACD", "Lemon Chiffon", "Yellow" },
        new [] { "968428", "Lemon Ginger", "Yellow" },
        new [] { "999A86", "Lemon Grass", "Green" },
        new [] { "2E3749", "Licorice", "Blue" },
        new [] { "ADD8E6", "Light Blue", "Blue" },
        new [] { "F08080", "Light Coral", "Orange" },
        new [] { "E0FFFF", "Light Cyan", "Blue" },
        new [] { "EEDD82", "Light Goldenrod", "Yellow" },
        new [] { "FAFAD2", "Light Goldenrod Yellow", "Yellow" },
        new [] { "90EE90", "Light Green", "Green" },
        new [] { "D3D3D3", "Light Grey", "Grey" },
        new [] { "FFB6C1", "Light Pink", "Red" },
        new [] { "FFA07A", "Light Salmon", "Orange" },
        new [] { "20B2AA", "Light Sea Green", "Green" },
        new [] { "87CEFA", "Light Sky Blue", "Blue" },
        new [] { "8470FF", "Light Slate Blue", "Blue" },
        new [] { "778899", "Light Slate Grey", "Grey" },
        new [] { "B0C4DE", "Light Steel Blue", "Blue" },
        new [] { "856363", "Light Wood", "Brown" },
        new [] { "FFFFE0", "Light Yellow", "Yellow" },
        new [] { "F7A233", "Lightning Yellow", "Yellow" },
        new [] { "C8A2C8", "Lilac", "Violet" },
        new [] { "9470C4", "Lilac Bush", "Violet" },
        new [] { "C19FB3", "Lily", "Violet" },
        new [] { "E9EEEB", "Lily White", "Grey" },
        new [] { "7AAC21", "Lima", "Green" },
        new [] { "00FF00", "Lime", "Green" },
        new [] { "32CD32", "Lime Green", "Green" },
        new [] { "5F9727", "Limeade", "Green" },
        new [] { "89AC27", "Limerick", "Green" },
        new [] { "FAF0E6", "Linen", "White" },
        new [] { "C7CDD8", "Link Water", "Blue" },
        new [] { "962C54", "Lipstick", "Red" },
        new [] { "534B4F", "Liver", "Brown" },
        new [] { "312A29", "Livid Brown", "Brown" },
        new [] { "DBD9C2", "Loafer", "Green" },
        new [] { "B3BBB7", "Loblolly", "Green" },
        new [] { "489084", "Lochinvar", "Green" },
        new [] { "316EA0", "Lochmara", "Blue" },
        new [] { "A2A580", "Locust", "Green" },
        new [] { "393E2E", "Log Cabin", "Green" },
        new [] { "9D9CB4", "Logan", "Blue" },
        new [] { "B9ACBB", "Lola", "Violet" },
        new [] { "AE94AB", "London Hue", "Violet" },
        new [] { "522426", "Lonestar", "Red" },
        new [] { "8B504B", "Lotus", "Brown" },
        new [] { "4C3347", "Loulou", "Violet" },
        new [] { "AB9A1C", "Lucky", "Green" },
        new [] { "292D4F", "Lucky Point", "Blue" },
        new [] { "4E5541", "Lunar Green", "Green" },
        new [] { "782E2C", "Lusty", "Red" },
        new [] { "AB8D3F", "Luxor Gold", "Yellow" },
        new [] { "697D89", "Lynch", "Blue" },
        new [] { "CBE8E8", "Mabel", "Blue" },
        new [] { "FFB97B", "Macaroni And Cheese", "Orange" },
        new [] { "B7E3A8", "Madang", "Green" },
        new [] { "2D3C54", "Madison", "Blue" },
        new [] { "473E23", "Madras", "Brown" },
        new [] { "FF00FF", "Magenta", "Violet" },
        new [] { "AAF0D1", "Magic Mint", "Green" },
        new [] { "F8F4FF", "Magnolia", "White" },
        new [] { "CA3435", "Mahogany", "Brown" },
        new [] { "A56531", "Mai Tai", "Orange" },
        new [] { "2A2922", "Maire", "Yellow" },
        new [] { "E3B982", "Maize", "Yellow" },
        new [] { "695F50", "Makara", "Brown" },
        new [] { "505555", "Mako", "Grey" },
        new [] { "0BDA51", "Malachite", "Green" },
        new [] { "97976F", "Malachite Green", "Green" },
        new [] { "66B7E1", "Malibu", "Blue" },
        new [] { "3A4531", "Mallard", "Green" },
        new [] { "A59784", "Malta", "Brown" },
        new [] { "766D7C", "Mamba", "Violet" },
        new [] { "8D90A1", "Manatee", "Blue" },
        new [] { "B57B2E", "Mandalay", "Yellow" },
        new [] { "8E2323", "Mandarian Orange", "Orange" },
        new [] { "CD525B", "Mandy", "Red" },
        new [] { "F5B799", "Mandys Pink", "Orange" },
        new [] { "E77200", "Mango Tango", "Orange" },
        new [] { "E2AF80", "Manhattan", "Orange" },
        new [] { "7FC15C", "Mantis", "Green" },
        new [] { "96A793", "Mantle", "Green" },
        new [] { "E4DB55", "Manz", "Green" },
        new [] { "352235", "Mardi Gras", "Violet" },
        new [] { "B88A3D", "Marigold", "Yellow" },
        new [] { "42639F", "Mariner", "Blue" },
        new [] { "800000", "Maroon", "Brown" },
        new [] { "2B2E26", "Marshland", "Green" },
        new [] { "B7A8A3", "Martini", "Brown" },
        new [] { "3C3748", "Martinique", "Violet" },
        new [] { "EBC881", "Marzipan", "Yellow" },
        new [] { "57534B", "Masala", "Brown" },
        new [] { "365C7D", "Matisse", "Blue" },
        new [] { "8E4D45", "Matrix", "Red" },
        new [] { "524B4B", "Matterhorn", "Grey" },
        new [] { "E0B0FF", "Mauve", "Violet" },
        new [] { "915F6D", "Mauve Taupe", "Red" },
        new [] { "F091A9", "Mauvelous", "Red" },
        new [] { "C8B1C0", "Maverick", "Violet" },
        new [] { "73C2FB", "Maya Blue", "Blue" },
        new [] { "8C6338", "McKenzie", "Orange" },
        new [] { "66CDAA", "Medium Aquamarine", "Blue" },
        new [] { "0000CD", "Medium Blue", "Blue" },
        new [] { "AF4035", "Medium Carmine", "Red" },
        new [] { "EAEAAE", "Medium Goldenrod", "Yellow" },
        new [] { "BA55D3", "Medium Orchid", "Violet" },
        new [] { "9370DB", "Medium Purple", "Violet" },
        new [] { "3CB371", "Medium Sea Green", "Green" },
        new [] { "7B68EE", "Medium Slate Blue", "Blue" },
        new [] { "00FA9A", "Medium Spring Green", "Green" },
        new [] { "48D1CC", "Medium Turquoise", "Blue" },
        new [] { "C71585", "Medium Violet Red", "Red" },
        new [] { "A68064", "Medium Wood", "Brown" },
        new [] { "E0B7C2", "Melanie", "Red" },
        new [] { "342931", "Melanzane", "Violet" },
        new [] { "FEBAAD", "Melon", "Red" },
        new [] { "C3B9DD", "Melrose", "Violet" },
        new [] { "D5D2D1", "Mercury", "Grey" },
        new [] { "E1DBD0", "Merino", "Yellow" },
        new [] { "4F4E48", "Merlin", "Grey" },
        new [] { "73343A", "Merlot", "Red" },
        new [] { "554A3C", "Metallic Bronze", "Red" },
        new [] { "6E3D34", "Metallic Copper", "Red" },
        new [] { "D4AF37", "Metallic Gold", "Yellow" },
        new [] { "BB7431", "Meteor", "Orange" },
        new [] { "4A3B6A", "Meteorite", "Violet" },
        new [] { "9B3D3D", "Mexican Red", "Red" },
        new [] { "666A6D", "Mid Grey", "Grey" },
        new [] { "21303E", "Midnight", "Blue" },
        new [] { "191970", "Midnight Blue", "Blue" },
        new [] { "21263A", "Midnight Express", "Blue" },
        new [] { "242E28", "Midnight Moss", "Green" },
        new [] { "3F3623", "Mikado", "Brown" },
        new [] { "F6F493", "Milan", "Green" },
        new [] { "9E3332", "Milano Red", "Red" },
        new [] { "F3E5C0", "Milk Punch", "Yellow" },
        new [] { "DCD9CD", "Milk White", "Grey" },
        new [] { "595648", "Millbrook", "Brown" },
        new [] { "F5F5CC", "Mimosa", "Green" },
        new [] { "DAEA6F", "Mindaro", "Green" },
        new [] { "373E41", "Mine Shaft", "Blue" },
        new [] { "506355", "Mineral Green", "Green" },
        new [] { "407577", "Ming", "Green" },
        new [] { "3E3267", "Minsk", "Violet" },
        new [] { "F5FFFA", "Mint Cream", "White" },
        new [] { "98FF98", "Mint Green", "Green" },
        new [] { "E0D8A7", "Mint Julep", "Green" },
        new [] { "C6EADD", "Mint Tulip", "Green" },
        new [] { "373F43", "Mirage", "Blue" },
        new [] { "A5A9B2", "Mischka", "Blue" },
        new [] { "BAB9A9", "Mist Grey", "Grey" },
        new [] { "FFE4E1", "Misty Rose", "Violet" },
        new [] { "605A67", "Mobster", "Violet" },
        new [] { "582F2B", "Moccaccino", "Red" },
        new [] { "FFE4B5", "Moccasin", "Yellow" },
        new [] { "6F372D", "Mocha", "Red" },
        new [] { "97463C", "Mojo", "Red" },
        new [] { "FF9889", "Mona Lisa", "Red" },
        new [] { "6B252C", "Monarch", "Red" },
        new [] { "554D42", "Mondo", "Brown" },
        new [] { "A58B6F", "Mongoose", "Brown" },
        new [] { "7A7679", "Monsoon", "Grey" },
        new [] { "393B3C", "Montana", "Grey" },
        new [] { "7AC5B4", "Monte Carlo", "Green" },
        new [] { "8378C7", "Moody Blue", "Violet" },
        new [] { "F5F3CE", "Moon Glow", "Green" },
        new [] { "CECDB8", "Moon Mist", "Green" },
        new [] { "C0B2D7", "Moon Raker", "Violet" },
        new [] { "F0C420", "Moon Yellow", "Yellow" },
        new [] { "9ED1D3", "Morning Glory", "Blue" },
        new [] { "442D21", "Morocco Brown", "Brown" },
        new [] { "565051", "Mortar", "Grey" },
        new [] { "005F5B", "Mosque", "Green" },
        new [] { "ADDFAD", "Moss Green", "Green" },
        new [] { "1AB385", "Mountain Meadow", "Green" },
        new [] { "A09F9C", "Mountain Mist", "Grey" },
        new [] { "997A8D", "Mountbatten Pink", "Violet" },
        new [] { "A9844F", "Muddy Waters", "Yellow" },
        new [] { "9E7E53", "Muesli", "Brown" },
        new [] { "C54B8C", "Mulberry", "Violet" },
        new [] { "884F40", "Mule Fawn", "Brown" },
        new [] { "524D5B", "Mulled Wine", "Violet" },
        new [] { "FFDB58", "Mustard", "Yellow" },
        new [] { "D68B80", "My Pink", "Red" },
        new [] { "FDAE45", "My Sin", "Yellow" },
        new [] { "21421E", "Myrtle", "Green" },
        new [] { "D8DDDA", "Mystic", "Grey" },
        new [] { "4E5D4E", "Nandor", "Green" },
        new [] { "A39A87", "Napa", "Yellow" },
        new [] { "E9E6DC", "Narvik", "Green" },
        new [] { "FFDEAD", "Navajo White", "Brown" },
        new [] { "000080", "Navy", "Blue" },
        new [] { "0066CC", "Navy Blue", "Blue" },
        new [] { "B8C6BE", "Nebula", "Green" },
        new [] { "EEC7A2", "Negroni", "Orange" },
        new [] { "4D4DFF", "Neon Blue", "Blue" },
        new [] { "FF9933", "Neon Carrot", "Orange" },
        new [] { "FF6EC7", "Neon Pink", "Violet" },
        new [] { "93AAB9", "Nepal", "Blue" },
        new [] { "77A8AB", "Neptune", "Green" },
        new [] { "252525", "Nero", "Grey" },
        new [] { "AAA583", "Neutral Green", "Green" },
        new [] { "666F6F", "Nevada", "Grey" },
        new [] { "6D3B24", "New Amber", "Orange" },
        new [] { "00009C", "New Midnight Blue", "Blue" },
        new [] { "E4C385", "New Orleans", "Yellow" },
        new [] { "EBC79E", "New Tan", "Brown" },
        new [] { "DD8374", "New York Pink", "Red" },
        new [] { "29A98B", "Niagara", "Green" },
        new [] { "332E2E", "Night Rider", "Grey" },
        new [] { "A23D54", "Night Shadz", "Red" },
        new [] { "253F4E", "Nile Blue", "Blue" },
        new [] { "A99D9D", "Nobel", "Grey" },
        new [] { "A19986", "Nomad", "Yellow" },
        new [] { "1D393C", "Nordic", "Blue" },
        new [] { "A4B88F", "Norway", "Green" },
        new [] { "BC9229", "Nugget", "Yellow" },
        new [] { "7E4A3B", "Nutmeg", "Brown" },
        new [] { "FCEDC5", "Oasis", "Yellow" },
        new [] { "008F70", "Observatory", "Green" },
        new [] { "4CA973", "Ocean Green", "Green" },
        new [] { "CC7722", "Ochre", "Brown" },
        new [] { "DFF0E2", "Off Green", "Green" },
        new [] { "FAF3DC", "Off Yellow", "Yellow" },
        new [] { "313330", "Oil", "Grey" },
        new [] { "8A3335", "Old Brick", "Red" },
        new [] { "73503B", "Old Copper", "Red" },
        new [] { "CFB53B", "Old Gold", "Yellow" },
        new [] { "FDF5E6", "Old Lace", "White" },
        new [] { "796878", "Old Lavender", "Violet" },
        new [] { "C02E4C", "Old Rose", "Red" },
        new [] { "808000", "Olive", "Green" },
        new [] { "6B8E23", "Olive Drab", "Green" },
        new [] { "B5B35C", "Olive Green", "Green" },
        new [] { "888064", "Olive Haze", "Yellow" },
        new [] { "747028", "Olivetone", "Green" },
        new [] { "9AB973", "Olivine", "Orange" },
        new [] { "C2E6EC", "Onahau", "Blue" },
        new [] { "48412B", "Onion", "Yellow" },
        new [] { "A8C3BC", "Opal", "Green" },
        new [] { "987E7E", "Opium", "Brown" },
        new [] { "395555", "Oracle", "Green" },
        new [] { "FFA500", "Orange", "Orange" },
        new [] { "FFA000", "Orange Peel", "Orange" },
        new [] { "FF4500", "Orange Red", "Orange" },
        new [] { "A85335", "Orange Roughy", "Orange" },
        new [] { "EAE3CD", "Orange White", "Yellow" },
        new [] { "DA70D6", "Orchid", "Violet" },
        new [] { "F1EBD9", "Orchid White", "Yellow" },
        new [] { "255B77", "Orient", "Blue" },
        new [] { "C28E88", "Oriental Pink", "Red" },
        new [] { "D2D3B3", "Orinoco", "Green" },
        new [] { "818988", "Oslo Grey", "Grey" },
        new [] { "D3DBCB", "Ottoman", "Green" },
        new [] { "2D383A", "Outer Space", "Grey" },
        new [] { "FF6037", "Outrageous Orange", "Orange" },
        new [] { "28353A", "Oxford Blue", "Blue" },
        new [] { "6D9A78", "Oxley", "Green" },
        new [] { "D1EAEA", "Oyster Bay", "Blue" },
        new [] { "D4B5B0", "Oyster Pink", "Red" },
        new [] { "864B36", "Paarl", "Orange" },
        new [] { "7A715C", "Pablo", "Yellow" },
        new [] { "009DC4", "Pacific Blue", "Blue" },
        new [] { "4F4037", "Paco", "Brown" },
        new [] { "7EB394", "Padua", "Green" },
        new [] { "682860", "Palatinate Purple", "Violet" },
        new [] { "987654", "Pale Brown", "Brown" },
        new [] { "DDADAF", "Pale Chestnut", "Red" },
        new [] { "ABCDEF", "Pale Cornflower Blue", "Blue" },
        new [] { "EEE8AA", "Pale Goldenrod", "Yellow" },
        new [] { "98FB98", "Pale Green", "Green" },
        new [] { "BDCAA8", "Pale Leaf", "Green" },
        new [] { "F984E5", "Pale Magenta", "Violet" },
        new [] { "9C8D72", "Pale Oyster", "Brown" },
        new [] { "FADADD", "Pale Pink", "Red" },
        new [] { "F9F59F", "Pale Prim", "Green" },
        new [] { "EFD6DA", "Pale Rose", "Red" },
        new [] { "636D70", "Pale Sky", "Blue" },
        new [] { "C3BEBB", "Pale Slate", "Grey" },
        new [] { "BC987E", "Pale Taupe", "Grey" },
        new [] { "AFEEEE", "Pale Turquoise", "Blue" },
        new [] { "DB7093", "Pale Violet Red", "Red" },
        new [] { "20392C", "Palm Green", "Green" },
        new [] { "36482F", "Palm Leaf", "Green" },
        new [] { "EAE4DC", "Pampas", "Grey" },
        new [] { "EBF7E4", "Panache", "Green" },
        new [] { "DFB992", "Pancho", "Orange" },
        new [] { "544F3A", "Panda", "Yellow" },
        new [] { "FFEFD5", "Papaya Whip", "Yellow" },
        new [] { "7C2D37", "Paprika", "Red" },
        new [] { "488084", "Paradiso", "Green" },
        new [] { "D0C8B0", "Parchment", "Yellow" },
        new [] { "FBEB50", "Paris Daisy", "Green" },
        new [] { "312760", "Paris M", "Violet" },
        new [] { "BFCDC0", "Paris White", "Green" },
        new [] { "305D35", "Parsley", "Green" },
        new [] { "77DD77", "Pastel Green", "Green" },
        new [] { "639283", "Patina", "Green" },
        new [] { "D3E5EF", "Pattens Blue", "Blue" },
        new [] { "2A2551", "Paua", "Violet" },
        new [] { "BAAB87", "Pavlova", "Yellow" },
        new [] { "404048", "Payne's Grey", "Grey" },
        new [] { "FFCBA4", "Peach", "Orange" },
        new [] { "FFDAB9", "Peach Puff", "Yellow" },
        new [] { "FFCC99", "Peach-Orange", "Orange" },
        new [] { "FADFAD", "Peach-Yellow", "Yellow" },
        new [] { "7A4434", "Peanut", "Brown" },
        new [] { "D1E231", "Pear", "Yellow" },
        new [] { "DED1C6", "Pearl Bush", "Orange" },
        new [] { "EAE0C8", "Pearl Lusta", "Yellow" },
        new [] { "766D52", "Peat", "Yellow" },
        new [] { "2599B2", "Pelorous", "Blue" },
        new [] { "D7E7D0", "Peppermint", "Green" },
        new [] { "ACB9E8", "Perano", "Blue" },
        new [] { "C2A9DB", "Perfume", "Violet" },
        new [] { "ACB6B2", "Periglacial Blue", "Green" },
        new [] { "C3CDE6", "Periwinkle", "Blue" },
        new [] { "1C39BB", "Persian Blue", "Blue" },
        new [] { "00A693", "Persian Green", "Green" },
        new [] { "32127A", "Persian Indigo", "Violet" },
        new [] { "F77FBE", "Persian Pink", "Red" },
        new [] { "683332", "Persian Plum", "Red" },
        new [] { "CC3333", "Persian Red", "Red" },
        new [] { "FE28A2", "Persian Rose", "Red" },
        new [] { "EC5800", "Persimmon", "Red" },
        new [] { "CD853F", "Peru", "Brown" },
        new [] { "733D1F", "Peru Tan", "Orange" },
        new [] { "7A7229", "Pesto", "Yellow" },
        new [] { "DA9790", "Petite Orchid", "Red" },
        new [] { "91A092", "Pewter", "Green" },
        new [] { "826663", "Pharlap", "Brown" },
        new [] { "F8EA97", "Picasso", "Green" },
        new [] { "5BA0D0", "Picton Blue", "Blue" },
        new [] { "FDD7E4", "Pig Pink", "Red" },
        new [] { "00A550", "Pigment Green", "Green" },
        new [] { "756556", "Pine Cone", "Brown" },
        new [] { "BDC07E", "Pine Glade", "Green" },
        new [] { "01796F", "Pine Green", "Green" },
        new [] { "2A2F23", "Pine Tree", "Green" },
        new [] { "FFC0CB", "Pink", "Red" },
        new [] { "FF66FF", "Pink Flamingo", "Red" },
        new [] { "D8B4B6", "Pink Flare", "Red" },
        new [] { "F6CCD7", "Pink Lace", "Red" },
        new [] { "F3D7B6", "Pink Lady", "Orange" },
        new [] { "BFB3B2", "Pink Swan", "Grey" },
        new [] { "9D5432", "Piper", "Orange" },
        new [] { "F5E6C4", "Pipi", "Yellow" },
        new [] { "FCDBD2", "Pippin", "Red" },
        new [] { "BA782A", "Pirate Gold", "Yellow" },
        new [] { "BBCDA5", "Pixie Green", "Green" },
        new [] { "E57F3D", "Pizazz", "Orange" },
        new [] { "BF8D3C", "Pizza", "Yellow" },
        new [] { "3E594C", "Plantation", "Green" },
        new [] { "DDA0DD", "Plum", "Violet" },
        new [] { "651C26", "Pohutukawa", "Red" },
        new [] { "E5F2E7", "Polar", "Green" },
        new [] { "8AA7CC", "Polo Blue", "Blue" },
        new [] { "6A1F44", "Pompadour", "Violet" },
        new [] { "DDDCDB", "Porcelain", "Grey" },
        new [] { "DF9D5B", "Porsche", "Orange" },
        new [] { "3B436C", "Port Gore", "Blue" },
        new [] { "F4F09B", "Portafino", "Green" },
        new [] { "8B98D8", "Portage", "Blue" },
        new [] { "F0D555", "Portica", "Yellow" },
        new [] { "EFDCD4", "Pot Pourri", "Orange" },
        new [] { "845C40", "Potters Clay", "Brown" },
        new [] { "B0E0E6", "Powder Blue", "Blue" },
        new [] { "883C32", "Prairie Sand", "Red" },
        new [] { "CAB4D4", "Prelude", "Violet" },
        new [] { "E2CDD5", "Prim", "Violet" },
        new [] { "E4DE8E", "Primrose", "Green" },
        new [] { "F8F6DF", "Promenade", "Green" },
        new [] { "F6E3DA", "Provincial Pink", "Orange" },
        new [] { "003366", "Prussian Blue", "Blue" },
        new [] { "DD00FF", "Psychedelic Purple", "Violet" },
        new [] { "CC8899", "Puce", "Red" },
        new [] { "6E3326", "Pueblo", "Orange" },
        new [] { "59BAA3", "Puerto Rico", "Green" },
        new [] { "BAC0B4", "Pumice", "Green" },
        new [] { "FF7518", "Pumpkin", "Orange" },
        new [] { "534931", "Punga", "Yellow" },
        new [] { "800080", "Purple", "Violet" },
        new [] { "652DC1", "Purple Heart", "Violet" },
        new [] { "9678B6", "Purple Mountain's Majesty", "Violet" },
        new [] { "50404D", "Purple Taupe", "Grey" },
        new [] { "CDAE70", "Putty", "Yellow" },
        new [] { "F2EDDD", "Quarter Pearl Lusta", "Green" },
        new [] { "EBE2D2", "Quarter Spanish White", "Yellow" },
        new [] { "D9D9F3", "Quartz", "White" },
        new [] { "C3988B", "Quicksand", "Brown" },
        new [] { "CBC9C0", "Quill Grey", "Grey" },
        new [] { "6A5445", "Quincy", "Brown" },
        new [] { "232F2C", "Racing Green", "Green" },
        new [] { "FF355E", "Radical Red", "Red" },
        new [] { "DCC6A0", "Raffia", "Yellow" },
        new [] { "667028", "Rain Forest", "Green" },
        new [] { "B3C1B1", "Rainee", "Green" },
        new [] { "FCAE60", "Rajah", "Orange" },
        new [] { "2B2E25", "Rangoon Green", "Green" },
        new [] { "6F747B", "Raven", "Blue" },
        new [] { "D27D46", "Raw Sienna", "Brown" },
        new [] { "734A12", "Raw Umber", "Brown" },
        new [] { "FF33CC", "Razzle Dazzle Rose", "Red" },
        new [] { "E30B5C", "Razzmatazz", "Red" },
        new [] { "453430", "Rebel", "Brown" },
        new [] { "FF0000", "Red", "Red" },
        new [] { "701F28", "Red Berry", "Red" },
        new [] { "CB6F4A", "Red Damask", "Orange" },
        new [] { "662A2C", "Red Devil", "Red" },
        new [] { "FF3F34", "Red Orange", "Orange" },
        new [] { "5D1F1E", "Red Oxide", "Red" },
        new [] { "7D4138", "Red Robin", "Red" },
        new [] { "AD522E", "Red Stage", "Orange" },
        new [] { "BB3385", "Medium Red Violet", "Violet" },
        new [] { "5B342E", "Redwood", "Red" },
        new [] { "D1EF9F", "Reef", "Green" },
        new [] { "A98D36", "Reef Gold", "Yellow" },
        new [] { "203F58", "Regal Blue", "Blue" },
        new [] { "798488", "Regent Grey", "Blue" },
        new [] { "A0CDD9", "Regent St Blue", "Blue" },
        new [] { "F6DEDA", "Remy", "Red" },
        new [] { "B26E33", "Reno Sand", "Orange" },
        new [] { "323F75", "Resolution Blue", "Blue" },
        new [] { "37363F", "Revolver", "Violet" },
        new [] { "3D4653", "Rhino", "Blue" },
        new [] { "EFECDE", "Rice Cake", "Green" },
        new [] { "EFF5D1", "Rice Flower", "Green" },
        new [] { "5959AB", "Rich Blue", "Blue" },
        new [] { "A15226", "Rich Gold", "Orange" },
        new [] { "B7C61A", "Rio Grande", "Green" },
        new [] { "89D9C8", "Riptide", "Green" },
        new [] { "556061", "River Bed", "Blue" },
        new [] { "DDAD56", "Rob Roy", "Yellow" },
        new [] { "00CCCC", "Robin's Egg Blue", "Blue" },
        new [] { "5A4D41", "Rock", "Brown" },
        new [] { "93A2BA", "Rock Blue", "Blue" },
        new [] { "9D442D", "Rock Spray", "Orange" },
        new [] { "C7A384", "Rodeo Dust", "Brown" },
        new [] { "6D7876", "Rolling Stone", "Green" },
        new [] { "D8625B", "Roman", "Red" },
        new [] { "7D6757", "Roman Coffee", "Brown" },
        new [] { "F4F0E6", "Romance", "Grey" },
        new [] { "FFC69E", "Romantic", "Orange" },
        new [] { "EAB852", "Ronchi", "Yellow" },
        new [] { "A14743", "Roof Terracotta", "Red" },
        new [] { "8E593C", "Rope", "Orange" },
        new [] { "D3A194", "Rose", "Red" },
        new [] { "FEAB9A", "Rose Bud", "Red" },
        new [] { "8A2D52", "Rose Bud Cherry", "Red" },
        new [] { "AC512D", "Rose Of Sharon", "Orange" },
        new [] { "905D5D", "Rose Taupe", "Violet" },
        new [] { "FBEEE8", "Rose White", "Red" },
        new [] { "BC8F8F", "Rosy Brown", "Brown" },
        new [] { "B69642", "Roti", "Yellow" },
        new [] { "A94064", "Rouge", "Red" },
        new [] { "4169E1", "Royal Blue", "Blue" },
        new [] { "B54B73", "Royal Heath", "Red" },
        new [] { "6B3FA0", "Royal Purple", "Violet" },
        new [] { "E0115F", "Ruby", "Red" },
        new [] { "716675", "Rum", "Violet" },
        new [] { "F1EDD4", "Rum Swizzle", "Green" },
        new [] { "80461B", "Russet", "Brown" },
        new [] { "7D655C", "Russett", "Brown" },
        new [] { "B7410E", "Rust", "Red" },
        new [] { "3A181A", "Rustic Red", "Red" },
        new [] { "8D5F2C", "Rusty Nail", "Orange" },
        new [] { "5D4E46", "Saddle", "Brown" },
        new [] { "8B4513", "Saddle Brown", "Brown" },
        new [] { "FF6600", "Safety Orange", "Orange" },
        new [] { "F4C430", "Saffron", "Yellow" },
        new [] { "989F7A", "Sage", "Green" },
        new [] { "B79826", "Sahara", "Yellow" },
        new [] { "A5CEEC", "Sail", "Blue" },
        new [] { "177B4D", "Salem", "Green" },
        new [] { "FA8072", "Salmon", "Red" },
        new [] { "FFD67B", "Salomie", "Yellow" },
        new [] { "696268", "Salt Box", "Violet" },
        new [] { "EEF3E5", "Saltpan", "Grey" },
        new [] { "3B2E25", "Sambuca", "Brown" },
        new [] { "2C6E31", "San Felix", "Green" },
        new [] { "445761", "San Juan", "Blue" },
        new [] { "4E6C9D", "San Marino", "Blue" },
        new [] { "867665", "Sand Dune", "Brown" },
        new [] { "A3876A", "Sandal", "Brown" },
        new [] { "AF937D", "Sandrift", "Brown" },
        new [] { "786D5F", "Sandstone", "Brown" },
        new [] { "DECB81", "Sandwisp", "Yellow" },
        new [] { "FEDBB7", "Sandy Beach", "Orange" },
        new [] { "F4A460", "Sandy Brown", "Brown" },
        new [] { "92000A", "Sangria", "Red" },
        new [] { "6C3736", "Sanguine Brown", "Red" },
        new [] { "9998A7", "Santas Grey", "Blue" },
        new [] { "A96A50", "Sante Fe", "Orange" },
        new [] { "E1D5A6", "Sapling", "Yellow" },
        new [] { "082567", "Sapphire", "Blue" },
        new [] { "555B2C", "Saratoga", "Green" },
        new [] { "F4EAE4", "Sauvignon", "Red" },
        new [] { "F5DEC4", "Sazerac", "Orange" },
        new [] { "6F63A0", "Scampi", "Violet" },
        new [] { "ADD9D1", "Scandal", "Green" },
        new [] { "FF2400", "Scarlet", "Red" },
        new [] { "4A2D57", "Scarlet Gum", "Violet" },
        new [] { "7E2530", "Scarlett", "Red" },
        new [] { "6B6A6C", "Scarpa Flow", "Grey" },
        new [] { "87876F", "Schist", "Green" },
        new [] { "FFD800", "School Bus Yellow", "Yellow" },
        new [] { "8D8478", "Schooner", "Brown" },
        new [] { "308EA0", "Scooter", "Blue" },
        new [] { "6A6466", "Scorpion", "Grey" },
        new [] { "EEE7C8", "Scotch Mist", "Yellow" },
        new [] { "66FF66", "Screamin' Green", "Green" },
        new [] { "3D4031", "Scrub", "Green" },
        new [] { "EF9548", "Sea Buckthorn", "Orange" },
        new [] { "DFDDD6", "Sea Fog", "Grey" },
        new [] { "2E8B57", "Sea Green", "Green" },
        new [] { "C2D5C4", "Sea Mist", "Green" },
        new [] { "8AAEA4", "Sea Nymph", "Green" },
        new [] { "DB817E", "Sea Pink", "Red" },
        new [] { "77B7D0", "Seagull", "Blue" },
        new [] { "321414", "Seal Brown", "Brown" },
        new [] { "69326E", "Seance", "Violet" },
        new [] { "FFF5EE", "Seashell", "White" },
        new [] { "37412A", "Seaweed", "Green" },
        new [] { "E6DFE7", "Selago", "Violet" },
        new [] { "FFBA00", "Selective Yellow", "Yellow" },
        new [] { "6B4226", "Semi-Sweet Chocolate", "Brown" },
        new [] { "9E5B40", "Sepia", "Brown" },
        new [] { "FCE9D7", "Serenade", "Orange" },
        new [] { "837050", "Shadow", "Green" },
        new [] { "9AC0B6", "Shadow Green", "Green" },
        new [] { "9F9B9D", "Shady Lady", "Grey" },
        new [] { "609AB8", "Shakespeare", "Blue" },
        new [] { "F8F6A8", "Shalimar", "Green" },
        new [] { "33CC99", "Shamrock", "Green" },
        new [] { "009E60", "Shamrock Green", "Green" },
        new [] { "34363A", "Shark", "Grey" },
        new [] { "00494E", "Sherpa Blue", "Green" },
        new [] { "1B4636", "Sherwood Green", "Green" },
        new [] { "E6B2A6", "Shilo", "Red" },
        new [] { "745937", "Shingle Fawn", "Brown" },
        new [] { "7988AB", "Ship Cove", "Blue" },
        new [] { "4E4E4C", "Ship Grey", "Grey" },
        new [] { "842833", "Shiraz", "Red" },
        new [] { "E899BE", "Shocking", "Violet" },
        new [] { "FC0FC0", "Shocking Pink", "Red" },
        new [] { "61666B", "Shuttle Grey", "Grey" },
        new [] { "686B50", "Siam", "Green" },
        new [] { "E9D9A9", "Sidecar", "Yellow" },
        new [] { "A0522D", "Sienna", "Brown" },
        new [] { "BBADA1", "Silk", "Brown" },
        new [] { "C0C0C0", "Silver", "Grey" },
        new [] { "ACAEA9", "Silver Chalice", "Grey" },
        new [] { "BEBDB6", "Silver Sand", "Grey" },
        new [] { "67BE90", "Silver Tree", "Green" },
        new [] { "A6D5D0", "Sinbad", "Green" },
        new [] { "69293B", "Siren", "Red" },
        new [] { "68766E", "Sirocco", "Green" },
        new [] { "C5BAA0", "Sisal", "Yellow" },
        new [] { "9DB4AA", "Skeptic", "Green" },
        new [] { "87CEEB", "Sky Blue", "Blue" },
        new [] { "6A5ACD", "Slate Blue", "Blue" },
        new [] { "708090", "Slate Grey", "Grey" },
        new [] { "42342B", "Slugger", "Brown" },
        new [] { "003399", "Smalt", "Blue" },
        new [] { "496267", "Smalt Blue", "Blue" },
        new [] { "BB5F34", "Smoke Tree", "Orange" },
        new [] { "605D6B", "Smoky", "Violet" },
        new [] { "FFFAFA", "Snow", "White" },
        new [] { "E3E3DC", "Snow Drift", "Grey" },
        new [] { "EAF7C9", "Snow Flurry", "Green" },
        new [] { "D6F0CD", "Snowy Mint", "Green" },
        new [] { "E4D7E5", "Snuff", "Violet" },
        new [] { "ECE5DA", "Soapstone", "Grey" },
        new [] { "CFBEA5", "Soft Amber", "Yellow" },
        new [] { "EEDFDE", "Soft Peach", "Red" },
        new [] { "85494C", "Solid Pink", "Red" },
        new [] { "EADAC2", "Solitaire", "Yellow" },
        new [] { "E9ECF1", "Solitude", "Blue" },
        new [] { "DD6B38", "Sorbus", "Orange" },
        new [] { "9D7F61", "Sorrell Brown", "Brown" },
        new [] { "C9B59A", "Sour Dough", "Brown" },
        new [] { "6F634B", "Soya Bean", "Brown" },
        new [] { "4B433B", "Space Shuttle", "Brown" },
        new [] { "7B8976", "Spanish Green", "Green" },
        new [] { "DED1B7", "Spanish White", "Yellow" },
        new [] { "375D4F", "Spectra", "Green" },
        new [] { "6C4F3F", "Spice", "Brown" },
        new [] { "8B5F4D", "Spicy Mix", "Brown" },
        new [] { "FF1CAE", "Spicy Pink", "Red" },
        new [] { "B3C4D8", "Spindle", "Blue" },
        new [] { "F1D79E", "Splash", "Yellow" },
        new [] { "7ECDDD", "Spray", "Blue" },
        new [] { "A7FC00", "Spring Bud", "Green" },
        new [] { "00FF7F", "Spring Green", "Green" },
        new [] { "A3BD9C", "Spring Rain", "Green" },
        new [] { "F1F1C6", "Spring Sun", "Green" },
        new [] { "E9E1D9", "Spring Wood", "Grey" },
        new [] { "B8CA9D", "Sprout", "Green" },
        new [] { "A2A1AC", "Spun Pearl", "Blue" },
        new [] { "8F7D6B", "Squirrel", "Brown" },
        new [] { "325482", "St Tropaz", "Blue" },
        new [] { "858885", "Stack", "Grey" },
        new [] { "A0A197", "Star Dust", "Grey" },
        new [] { "D2C6B6", "Stark White", "Yellow" },
        new [] { "E3DD39", "Starship", "Green" },
        new [] { "4682B4", "Steel Blue", "Blue" },
        new [] { "43464B", "Steel Grey", "Grey" },
        new [] { "833D3E", "Stiletto", "Red" },
        new [] { "807661", "Stonewall", "Yellow" },
        new [] { "65645F", "Storm Dust", "Grey" },
        new [] { "747880", "Storm Grey", "Blue" },
        new [] { "DABE82", "Straw", "Yellow" },
        new [] { "946A81", "Strikemaster", "Violet" },
        new [] { "406356", "Stromboli", "Green" },
        new [] { "724AA1", "Studio", "Violet" },
        new [] { "8C9C9C", "Submarine", "Blue" },
        new [] { "EEEFDF", "Sugar Cane", "Green" },
        new [] { "C6EA80", "Sulu", "Green" },
        new [] { "8FB69C", "Summer Green", "Green" },
        new [] { "38B0DE", "Summer Sky", "Blue" },
        new [] { "EF8E38", "Sun", "Orange" },
        new [] { "C4AA4D", "Sundance", "Yellow" },
        new [] { "F8AFA9", "Sundown", "Red" },
        new [] { "DAC01A", "Sunflower", "Yellow" },
        new [] { "C76155", "Sunglo", "Red" },
        new [] { "FFCC33", "Sunglow", "Orange" },
        new [] { "C0514A", "Sunset", "Red" },
        new [] { "FE4C40", "Sunset Orange", "Orange" },
        new [] { "FA9D49", "Sunshade", "Orange" },
        new [] { "FFB437", "Supernova", "Yellow" },
        new [] { "B8D4BB", "Surf", "Green" },
        new [] { "C3D6BD", "Surf Crest", "Green" },
        new [] { "007B77", "Surfie Green", "Green" },
        new [] { "7C9F2F", "Sushi", "Green" },
        new [] { "8B8685", "Suva Grey", "Grey" },
        new [] { "252F2F", "Swamp", "Green" },
        new [] { "DAE6DD", "Swans Down", "Grey" },
        new [] { "F9E176", "Sweet Corn", "Yellow" },
        new [] { "EE918D", "Sweet Pink", "Red" },
        new [] { "D7CEC5", "Swirl", "Grey" },
        new [] { "DBD0CA", "Swiss Coffee", "Grey" },
        new [] { "F6AE78", "Tacao", "Orange" },
        new [] { "D2B960", "Tacha", "Yellow" },
        new [] { "DC722A", "Tahiti Gold", "Orange" },
        new [] { "D8CC9B", "Tahuna Sands", "Yellow" },
        new [] { "853534", "Tall Poppy", "Red" },
        new [] { "A39977", "Tallow", "Yellow" },
        new [] { "752B2F", "Tamarillo", "Red" },
        new [] { "D2B48C", "Tan", "Brown" },
        new [] { "B8B5A1", "Tana", "Green" },
        new [] { "1E2F3C", "Tangaroa", "Blue" },
        new [] { "F28500", "Tangerine", "Orange" },
        new [] { "FFCC00", "Tangerine Yellow", "Yellow" },
        new [] { "D46F31", "Tango", "Orange" },
        new [] { "7C7C72", "Tapa", "Green" },
        new [] { "B37084", "Tapestry", "Red" },
        new [] { "DEF1DD", "Tara", "Green" },
        new [] { "253C48", "Tarawera", "Blue" },
        new [] { "BAC0B3", "Tasman", "Grey" },
        new [] { "483C32", "Taupe", "Grey" },
        new [] { "8B8589", "Taupe Grey", "Grey" },
        new [] { "643A48", "Tawny Port", "Red" },
        new [] { "496569", "Tax Break", "Blue" },
        new [] { "2B4B40", "Te Papa Green", "Green" },
        new [] { "BFB5A2", "Tea", "Yellow" },
        new [] { "D0F0C0", "Tea Green", "Green" },
        new [] { "F883C2", "Tea Rose", "Orange" },
        new [] { "AB8953", "Teak", "Yellow" },
        new [] { "008080", "Teal", "Blue" },
        new [] { "254855", "Teal Blue", "Blue" },
        new [] { "3C2126", "Temptress", "Brown" },
        new [] { "CD5700", "Tenne (Tawny)", "Orange" },
        new [] { "F4D0A4", "Tequila", "Yellow" },
        new [] { "E2725B", "Terra Cotta", "Red" },
        new [] { "ECE67E", "Texas", "Green" },
        new [] { "FCB057", "Texas Rose", "Orange" },
        new [] { "B1948F", "Thatch", "Brown" },
        new [] { "544E31", "Thatch Green", "Yellow" },
        new [] { "D8BFD8", "Thistle", "Violet" },
        new [] { "4D4D4B", "Thunder", "Grey" },
        new [] { "923830", "Thunderbird", "Red" },
        new [] { "97422D", "Tia Maria", "Orange" },
        new [] { "B9C3BE", "Tiara", "Grey" },
        new [] { "184343", "Tiber", "Green" },
        new [] { "FC80A5", "Tickle Me Pink", "Red" },
        new [] { "F0F590", "Tidal", "Green" },
        new [] { "BEB4AB", "Tide", "Brown" },
        new [] { "324336", "Timber Green", "Green" },
        new [] { "D9D6CF", "Timberwolf", "Grey" },
        new [] { "DDD6E1", "Titan White", "Violet" },
        new [] { "9F715F", "Toast", "Brown" },
        new [] { "6D5843", "Tobacco Brown", "Brown" },
        new [] { "44362D", "Tobago", "Brown" },
        new [] { "3E2631", "Toledo", "Violet" },
        new [] { "2D2541", "Tolopea", "Violet" },
        new [] { "4F6348", "Tom Thumb", "Green" },
        new [] { "FF6347", "Tomato", "Red" },
        new [] { "E79E88", "Tonys Pink", "Orange" },
        new [] { "817C87", "Topaz", "Violet" },
        new [] { "FD0E35", "Torch Red", "Red" },
        new [] { "353D75", "Torea Bay", "Blue" },
        new [] { "374E88", "Tory Blue", "Blue" },
        new [] { "744042", "Tosca", "Red" },
        new [] { "9CACA5", "Tower Grey", "Green" },
        new [] { "6DAFA7", "Tradewind", "Green" },
        new [] { "DDEDE9", "Tranquil", "Blue" },
        new [] { "E2DDC7", "Travertine", "Green" },
        new [] { "E2813B", "Tree Poppy", "Orange" },
        new [] { "7E8424", "Trendy Green", "Green" },
        new [] { "805D80", "Trendy Pink", "Violet" },
        new [] { "C54F33", "Trinidad", "Orange" },
        new [] { "AEC9EB", "Tropical Blue", "Blue" },
        new [] { "00755E", "Tropical Rain Forest", "Green" },
        new [] { "4C5356", "Trout", "Grey" },
        new [] { "8E72C7", "True V", "Violet" },
        new [] { "454642", "Tuatara", "Grey" },
        new [] { "F9D3BE", "Tuft Bush", "Orange" },
        new [] { "E3AC3D", "Tulip Tree", "Yellow" },
        new [] { "DEA681", "Tumbleweed", "Brown" },
        new [] { "46494E", "Tuna", "Grey" },
        new [] { "585452", "Tundora", "Grey" },
        new [] { "F5CC23", "Turbo", "Yellow" },
        new [] { "A56E75", "Turkish Rose", "Red" },
        new [] { "AE9041", "Turmeric", "Yellow" },
        new [] { "40E0D0", "Turquoise", "Blue" },
        new [] { "6CDAE7", "Turquoise Blue", "Blue" },
        new [] { "363E1D", "Turtle Green", "Green" },
        new [] { "AD6242", "Tuscany", "Orange" },
        new [] { "E3E5B1", "Tusk", "Green" },
        new [] { "BF914B", "Tussock", "Yellow" },
        new [] { "F8E4E3", "Tutu", "Red" },
        new [] { "DAC0CD", "Twilight", "Violet" },
        new [] { "F4F6EC", "Twilight Blue", "Grey" },
        new [] { "C19156", "Twine", "Yellow" },
        new [] { "66023C", "Tyrian Purple", "Violet" },
        new [] { "FF6FFF", "Ultra Pink", "Red" },
        new [] { "120A8F", "Ultramarine", "Blue" },
        new [] { "D4574E", "Valencia", "Red" },
        new [] { "382C38", "Valentino", "Violet" },
        new [] { "2A2B41", "Valhalla", "Violet" },
        new [] { "523936", "Van Cleef", "Brown" },
        new [] { "CCB69B", "Vanilla", "Brown" },
        new [] { "EBD2D1", "Vanilla Ice", "Red" },
        new [] { "FDEFD3", "Varden", "Yellow" },
        new [] { "C80815", "Venetian Red", "Red" },
        new [] { "2C5778", "Venice Blue", "Blue" },
        new [] { "8B7D82", "Venus", "Violet" },
        new [] { "62603E", "Verdigris", "Grey" },
        new [] { "48531A", "Verdun Green", "Green" },
        new [] { "FF4D00", "Vermilion", "Red" },
        new [] { "5C4033", "Very Dark Brown", "Brown" },
        new [] { "CDCDCD", "Very Light Grey", "Grey" },
        new [] { "A85533", "Vesuvius", "Orange" },
        new [] { "564985", "Victoria", "Violet" },
        new [] { "5F9228", "Vida Loca", "Green" },
        new [] { "4DB1C8", "Viking", "Blue" },
        new [] { "955264", "Vin Rouge", "Red" },
        new [] { "C58F9D", "Viola", "Red" },
        new [] { "2E2249", "Violent Violet", "Violet" },
        new [] { "EE82EE", "Violet", "Violet" },
        new [] { "9F5F9F", "Violet Blue", "Violet" },
        new [] { "F7468A", "Violet Red", "Red" },
        new [] { "40826D", "Viridian", "Blue" },
        new [] { "4B5F56", "Viridian Green", "Green" },
        new [] { "F9E496", "Vis Vis", "Yellow" },
        new [] { "97D5B3", "Vista Blue", "Green" },
        new [] { "E3DFD9", "Vista White", "Grey" },
        new [] { "FF9980", "Vivid Tangerine", "Orange" },
        new [] { "803790", "Vivid Violet", "Violet" },
        new [] { "4E2728", "Volcano", "Red" },
        new [] { "443240", "Voodoo", "Violet" },
        new [] { "36383C", "Vulcan", "Grey" },
        new [] { "D4BBB1", "Wafer", "Orange" },
        new [] { "5B6E91", "Waikawa Grey", "Blue" },
        new [] { "4C4E31", "Waiouru", "Green" },
        new [] { "E4E2DC", "Wan White", "Grey" },
        new [] { "849137", "Wasabi", "Green" },
        new [] { "B6ECDE", "Water Leaf", "Green" },
        new [] { "006E4E", "Watercourse", "Green" },
        new [] { "D6CA3D", "Wattle", "Green" },
        new [] { "F2CDBB", "Watusi", "Orange" },
        new [] { "EEB39E", "Wax Flower", "Orange" },
        new [] { "FDD7D8", "We Peep", "Red" },
        new [] { "4C6B88", "Wedgewood", "Blue" },
        new [] { "8E3537", "Well Read", "Red" },
        new [] { "5C512F", "West Coast", "Yellow" },
        new [] { "E5823A", "West Side", "Orange" },
        new [] { "D4CFC5", "Westar", "Grey" },
        new [] { "F1919A", "Wewak", "Red" },
        new [] { "F5DEB3", "Wheat", "Brown" },
        new [] { "DFD7BD", "Wheatfield", "Yellow" },
        new [] { "D29062", "Whiskey", "Orange" },
        new [] { "D4915D", "Whiskey Sour", "Orange" },
        new [] { "EFE6E6", "Whisper", "Grey" },
        new [] { "FFFFFF", "White", "White" },
        new [] { "D7EEE4", "White Ice", "Green" },
        new [] { "E7E5E8", "White Lilac", "Blue" },
        new [] { "EEE7DC", "White Linen", "Grey" },
        new [] { "F8F6D8", "White Nectar", "Green" },
        new [] { "DAD6CC", "White Pointer", "Grey" },
        new [] { "D4CFB4", "White Rock", "Green" },
        new [] { "F5F5F5", "White Smoke", "White" },
        new [] { "7A89B8", "Wild Blue Yonder", "Blue" },
        new [] { "E3D474", "Wild Rice", "Green" },
        new [] { "E7E4DE", "Wild Sand", "Grey" },
        new [] { "FF3399", "Wild Strawberry", "Red" },
        new [] { "FD5B78", "Wild Watermelon", "Red" },
        new [] { "BECA60", "Wild Willow", "Green" },
        new [] { "53736F", "William", "Green" },
        new [] { "DFE6CF", "Willow Brook", "Green" },
        new [] { "69755C", "Willow Grove", "Green" },
        new [] { "462C77", "Windsor", "Violet" },
        new [] { "522C35", "Wine Berry", "Red" },
        new [] { "D0C383", "Winter Hazel", "Yellow" },
        new [] { "F9E8E2", "Wisp Pink", "Red" },
        new [] { "C9A0DC", "Wisteria", "Violet" },
        new [] { "A29ECD", "Wistful", "Blue" },
        new [] { "FBF073", "Witch Haze", "Green" },
        new [] { "302621", "Wood Bark", "Brown" },
        new [] { "463629", "Woodburn", "Brown" },
        new [] { "626746", "Woodland", "Green" },
        new [] { "45402B", "Woodrush", "Yellow" },
        new [] { "2B3230", "Woodsmoke", "Grey" },
        new [] { "554545", "Woody Brown", "Brown" },
        new [] { "75876E", "Xanadu", "Green" },
        new [] { "FFFF00", "Yellow", "Yellow" },
        new [] { "9ACD32", "Yellow Green", "Green" },
        new [] { "73633E", "Yellow Metal", "Yellow" },
        new [] { "FFAE42", "Yellow Orange", "Orange" },
        new [] { "F49F35", "Yellow Sea", "Yellow" },
        new [] { "FFC5BB", "Your Pink", "Red" },
        new [] { "826A21", "Yukon Gold", "Yellow" },
        new [] { "C7B882", "Yuma", "Yellow" },
        new [] { "6B5A5A", "Zambezi", "Brown" },
        new [] { "B2C6B1", "Zanah", "Green" },
        new [] { "C6723B", "Zest", "Orange" },
        new [] { "3B3C38", "Zeus", "Grey" },
        new [] { "81A6AA", "Ziggurat", "Blue" },
        new [] { "EBC2AF", "Zinnwaldite", "Brown" },
        new [] { "DEE3E3", "Zircon", "Grey" },
        new [] { "DDC283", "Zombie", "Yellow" },
        new [] { "A29589", "Zorba", "Brown" },
        new [] { "17462E", "Zuccini", "Green" },
        new [] { "CDD5D5", "Zumthor", "Grey" }
    };

    private static readonly string[][] ShadeTable = new[]
    {
        new [] { "FF0000", "Red" },
        new [] { "FFA500", "Orange" },
        new [] { "FFFF00", "Yellow" },
        new [] { "008000", "Green" },
        new [] { "0000FF", "Blue" },
        new [] { "EE82EE", "Violet" },
        new [] { "A52A2A", "Brown" },
        new [] { "000000", "Black" },
        new [] { "808080", "Grey" },
        new [] { "FFFFFF", "White"}
    };
}
